export type CatalogStatus = "필수" | "권장" | "보류";

export type CatalogItem = {
  label: string;
  korean?: string;
  note: string;
  status?: CatalogStatus;
  parent?: string;
};

export type CatalogGroup = {
  group: string;
  description: string;
  items: CatalogItem[];
};

export type SidebarStatus = "stable" | "deprecated" | "custom";

export type SidebarNode = {
  id: string;
  title: string;
  koTitle: string;
  href: string;
  depth: number;
  status: SidebarStatus;
  children?: SidebarNode[];
};

export type Token = {
  name: string;
  value: string;
  korean: string;
  usage: string;
};

export type IconSpec = {
  name: string;
  korean: string;
  size: string;
  usage: string;
};

type CatalogInput = string | [label: string, parent: string];
type SidebarInput =
  | string
  | {
      title: string;
      href?: string;
      status?: SidebarStatus;
      children?: SidebarInput[];
    };

const referenceStatus: Record<string, CatalogStatus> = {
  Modal: "보류",
  "Price Range": "보류",
};

const koreanNames: Record<string, string> = {
  Home: "홈",
  "Web Installation & Usage": "웹 설치 및 사용",
  "System Installation": "설치 가이드",
  "Guide to Web Components": "웹 컴포넌트 가이드",
  "Web Component Basics": "웹 컴포넌트 기본",
  "Style Customization": "스타일 커스터마이징",
  "Light DOM Style Considerations": "라이트 DOM 스타일 고려사항",
  "Working with Forms": "폼 작업",
  "Working with LiveView": "LiveView 작업",
  "React Components": "React 컴포넌트",
  "Next.js SSR": "Next.js SSR",
  "AI Agent Skill": "AI 에이전트 스킬",
  Changelog: "변경 이력",
  "Migrating From Spark": "Spark에서 이전",
  "Design Tokens": "디자인 토큰",
  Typography: "타이포그래피",
  Forms: "폼",
  "Dimensions/Layout": "치수/레이아웃",
  Lists: "리스트",
  Buttons: "버튼",
  "Style Guide": "스타일 가이드",
  Installation: "설치",
  Schema: "스키마",
  Color: "색상",
  Font: "폰트",
  Spacing: "간격",
  Size: "크기",
  Elevation: "그림자/고도",
  Motion: "모션",
  Breakpoints: "반응형 분기점",
  Icons: "아이콘",
  "UI Icons": "UI 아이콘",
  "Frequent Icons": "자주쓰는 아이콘",
  "Option Icons": "옵션 아이콘",
  "Vehicle Info Icons": "차량 관련 아이콘",
  "Brand Icons": "브랜드 아이콘",
  "Community Icons": "커뮤니티 아이콘",
  Imagery: "이미지",
  Layout: "레이아웃",
  "Typography & Headings": "타이포그래피와 제목",
  "Usability Standards": "사용성 기준",
  "Visual Language": "비주얼 언어",
  Components: "컴포넌트",
  Accordion: "아코디언",
  Badge: "배지",
  Breadcrumb: "브레드크럼",
  Button: "버튼",
  Callout: "콜아웃",
  Card: "카드",
  "Card Carousel": "카드 캐러셀",
  Checkbox: "체크박스",
  "Checkbox Lite": "체크박스 라이트",
  Disclaimer: "고지문",
  "Feedback Thumbs": "피드백 엄지",
  Fieldset: "필드셋",
  Figure: "피겨",
  Filter: "필터",
  "Form Module": "폼 모듈",
  Gallery: "갤러리",
  "Gallery Grid": "갤러리 그리드",
  "Gallery Thumbnails": "갤러리 썸네일",
  Headshot: "헤드샷",
  Input: "입력 필드",
  "Input Lite": "입력 필드 라이트",
  Link: "링크",
  "Link Pack": "링크 묶음",
  List: "목록",
  Menu: "메뉴",
  "Menu Item": "메뉴 항목",
  Modal: "모달",
  Notification: "알림",
  "Page Section": "페이지 섹션",
  Pagination: "페이지네이션",
  "Paging Button": "페이지 버튼",
  Picker: "피커",
  "Picker Option": "피커 옵션",
  Popover: "팝오버",
  "Price Range": "가격 범위",
  "Progress Bar": "진행 바",
  Radio: "라디오",
  "Radio Lite": "라디오 라이트",
  Range: "범위",
  "Range Dual": "이중 범위",
  Rating: "평점",
  "Rating Input": "평점 입력",
  Reveal: "펼쳐보기",
  Save: "저장/찜",
  Select: "셀렉트",
  "Select Lite": "셀렉트 라이트",
  Separator: "구분선",
  Spinner: "스피너",
  Stack: "스택",
  SVG: "SVG 아이콘",
  Switch: "스위치",
  Tabs: "탭",
  Tab: "탭 항목",
  "Tab Panel": "탭 패널",
  Textarea: "텍스트영역",
  "Textarea Lite": "텍스트영역 라이트",
  Tooltip: "툴팁",
  "plop:component": "컴포넌트 자동 생성 슬롯",
  Principles: "원칙",
  "Design Principles": "디자인 원칙",
  "Motion Principles": "모션 원칙",
  "Content Strategy": "콘텐츠 전략",
  "Content Strategy Principles": "콘텐츠 전략 원칙",
  "Voice and Tone": "보이스와 톤",
  "Grammar and Mechanics": "문법과 표기",
  Vocabulary: "용어집",
  Accessibility: "접근성",
  "Accessibility Principles": "접근성 원칙",
  "Accessibility Checklist": "접근성 체크리스트",
  "Global Code": "전역 코드",
  "Default Language": "기본 언어",
  "Semantic HTML": "시맨틱 HTML",
  "Unique Page Title Element": "고유 페이지 제목",
  "Keyboard Navigation": "키보드 탐색",
  "Focus State": "포커스 상태",
  "Keyboard Interaction": "키보드 상호작용",
  "Logical Tab Order": "논리적 탭 순서",
  "Minimum Contrast Ratio": "최소 명도 대비",
  "Text Contrast": "텍스트 대비",
  "Multi Device Responsive Design": "다중 기기 반응형",
  "Text Resizing": "텍스트 확대",
  "Touch Targets": "터치 타깃",
  "Moving, Flashing, or Blinking Content": "움직임/깜빡임 콘텐츠",
  "Content Flash": "콘텐츠 깜빡임",
  "Stop Motion": "모션 정지",
  Headings: "제목 구조",
  "Clear Headings": "명확한 제목",
  "Sequential Headings": "순차 제목",
  "Forms, Labels, and Errors": "폼 라벨 오류",
  "Form Errors": "폼 오류",
  "Form Labels": "폼 라벨",
  "Forms Keyboard Accessible": "폼 키보드 접근성",
  "Written Material (Copy)": "문구",
  "Clear Content": "명확한 콘텐츠",
  "Meaningful Link Text": "의미 있는 링크 텍스트",
  "Image Text Alternatives": "이미지 대체 텍스트",
  "Image Alt Text": "이미지 Alt 텍스트",
  "Color Contrast": "색상 대비",
  Resources: "자료",
  References: "참고 문서",
  "Coverage Matrix": "커버리지 매트릭스",
  Storybook: "스토리북",
  "QA Checklist": "QA 체크리스트",
  "Cars.com Cross-check": "Cars.com IA 대조",
  "Component IA": "컴포넌트 문서 구조",
  "Naming Gaps": "명칭 차이",
  "Migration Order": "이식 순서",
  Toolbox: "툴박스",
  Foundations: "파운데이션",
  "Design Token": "디자인 토큰",
  Iconography: "아이콘그래피",
  Gradient: "그라디언트",
  Radius: "모서리",
  State: "상태",
  Feedback: "피드백",
  "Inclusive Design": "포용적 디자인",
  "International Design": "국제화 디자인",
  "Mobile/App Components": "모바일/앱 컴포넌트",
  "Action Button": "액션 버튼",
  "Alert Dialog": "알림 다이얼로그",
  "Attachment Input": "첨부 입력",
  "Bottom Navigation": "하단 내비게이션",
  "Bottom Sheet": "하단 시트",
  "Content Placeholder": "콘텐츠 플레이스홀더",
  "Contextual Floating Button": "컨텍스트 플로팅 버튼",
  "Date Picker": "날짜 선택",
  Field: "필드",
  "Floating Action Button": "플로팅 액션 버튼",
  Footer: "푸터",
  "Help Bubble": "도움말 버블",
  "Identity Placeholder": "식별 플레이스홀더",
  "Image Frame": "이미지 프레임",
  "Input Button": "입력 버튼",
  "Manner Temp & Manner Temp Badge": "매너 온도/배지",
  "Menu Sheet": "메뉴 시트",
  "Notification Badge": "알림 배지",
  "Page Banner": "페이지 배너",
  "Progress Circle": "진행 원",
  "Quantity Picker": "수량 선택",
  "Reaction Button": "반응 버튼",
  "Result Section": "결과 섹션",
  "Scroll Fog": "스크롤 포그",
  "Segmented Control": "세그먼트 컨트롤",
  "Select Box": "셀렉트 박스",
  "Side Navigation": "사이드 내비게이션",
  "Side Panel": "사이드 패널",
  Skeleton: "스켈레톤",
  Slider: "슬라이더",
  "Table Pagination": "테이블 페이지네이션",
  "Tag Group": "태그 그룹",
  "Text Input & Textarea": "텍스트 입력/텍스트영역",
  "Time Picker": "시간 선택",
  "Top Navigation": "상단 내비게이션",
  "Wheel Picker": "휠 피커",
  "Bootstrap Cross-check": "Bootstrap 크로스체크",
  "Getting Started": "시작하기",
  Customize: "커스터마이즈",
  Content: "콘텐츠",
  Helpers: "헬퍼",
  Utilities: "유틸리티",
  "Bobaedream Admin": "보배드림 관리",
  Registry: "컴포넌트 등록/수정",
  "Measurement Master": "측정 마스터",
  "Vehicle Listing Patterns": "매물 리스트 패턴",
  "Vehicle Detail Patterns": "매물 상세 패턴",
  "Filter Patterns": "필터 패턴",
  "AI Measurement Workflow": "AI 측정 워크플로우",
  "Design System": "디자인 시스템",
  Overview: "개요",
  Status: "상태",
  Tokens: "토큰",
  Patterns: "패턴",
  Processes: "프로세스",
  "Change log": "변경 로그",
  Theming: "테마",
  Dimension: "치수",
  Shadow: "그림자",
  Shape: "형태",
  Opacity: "투명도",
  Illustration: "일러스트레이션",
  "Action bar": "액션 바",
  "Alert notice": "알림 노티스",
  "Inline notice": "인라인 노티스",
  "Page notice": "페이지 노티스",
  "Section notice": "섹션 노티스",
  Avatar: "아바타",
  Banner: "배너",
  "CTA button": "CTA 버튼",
  "Icon button": "아이콘 버튼",
  "Link button": "링크 버튼",
  Calendar: "캘린더",
  Carousel: "캐러셀",
  CCD: "CCD",
  Chip: "칩",
  "Filter chip": "필터 칩",
  "Input chip": "입력 칩",
  "Data visualization": "데이터 시각화",
  Graphs: "그래프",
  Metrics: "지표",
  Dialog: "다이얼로그",
  Alert: "경고",
  Confirmation: "확인",
  Standard: "표준",
  Divider: "디바이더",
  "Education notice": "교육 노티스",
  "EEK rating and range": "EEK 등급 및 범위",
  Expansion: "확장",
  Combobox: "콤보박스",
  "Date field": "날짜 필드",
  Dropdown: "드롭다운",
  "Numeric stepper": "숫자 스테퍼",
  Password: "비밀번호",
  "Phone number": "전화번호",
  "Radio button": "라디오 버튼",
  "Select list": "셀렉트 목록",
  "Text area": "텍스트 영역",
  "Text field": "텍스트 필드",
  "Item tile": "아이템 타일",
  "List row": "리스트 행",
  Loading: "로딩",
  "Expressive loader": "표현형 로더",
  "Skeleton loader": "스켈레톤 로더",
  "Media container": "미디어 컨테이너",
  Navigation: "내비게이션",
  "Top navigation bar": "상단 내비게이션 바",
  Panel: "패널",
  "Progress stepper": "진행 스테퍼",
  "Search field": "검색 필드",
  "Section header": "섹션 헤더",
  "Segmented button": "세그먼트 버튼",
  Sheet: "시트",
  "Context sheet": "컨텍스트 시트",
  "Focus sheet": "포커스 시트",
  Signal: "시그널",
  Snackbar: "스낵바",
  "State layer": "상태 레이어",
  Table: "테이블",
  Tip: "팁",
  Tourtip: "투어팁",
  "Toggle button group": "토글 버튼 그룹",
  "Video player": "비디오 플레이어",
  "Bulk editing": "일괄 편집",
  "Creating forms": "폼 작성",
  "Empty states": "빈 상태",
  Filtering: "필터링",
  "Requesting user feedback": "사용자 피드백 요청",
  "Uploading files": "파일 업로드",
  "Using links": "링크 사용",
  "Text link": "텍스트 링크",
  "Legal link": "법적 링크",
};

const requiredLabels = new Set([
  "Home",
  "Web Installation & Usage",
  "System Installation",
  "Guide to Web Components",
  "Web Component Basics",
  "Style Customization",
  "Working with Forms",
  "React Components",
  "AI Agent Skill",
  "Changelog",
  "Design Tokens",
  "Color",
  "Font",
  "Spacing",
  "Size",
  "Elevation",
  "Motion",
  "Breakpoints",
  "Icons",
  "Forms",
  "Imagery",
  "Layout",
  "Typography & Headings",
  "Usability Standards",
  "Visual Language",
  "Accordion",
  "Badge",
  "Breadcrumb",
  "Button",
  "Card",
  "Card Carousel",
  "Checkbox",
  "Fieldset",
  "Filter",
  "Form Module",
  "Gallery",
  "Gallery Grid",
  "Gallery Thumbnails",
  "Input",
  "Link",
  "List",
  "Menu",
  "Notification",
  "Pagination",
  "Picker",
  "Popover",
  "Progress Bar",
  "Radio",
  "Range",
  "Range Dual",
  "Rating",
  "Save",
  "Select",
  "Separator",
  "SVG",
  "Switch",
  "Tabs",
  "Textarea",
  "Tooltip",
  "Accessibility Principles",
  "Accessibility Checklist",
  "Global Code",
  "Default Language",
  "Semantic HTML",
  "Unique Page Title Element",
  "Keyboard Navigation",
  "Focus State",
  "Keyboard Interaction",
  "Logical Tab Order",
  "Minimum Contrast Ratio",
  "Text Contrast",
  "Multi Device Responsive Design",
  "Text Resizing",
  "Touch Targets",
  "Moving, Flashing, or Blinking Content",
  "Content Flash",
  "Stop Motion",
  "Headings",
  "Clear Headings",
  "Sequential Headings",
  "Forms, Labels, and Errors",
  "Form Errors",
  "Form Labels",
  "Forms Keyboard Accessible",
  "Written Material (Copy)",
  "Clear Content",
  "Meaningful Link Text",
  "Image Text Alternatives",
  "Image Alt Text",
  "Color Contrast",
]);

const fuseNotes: Record<string, string> = {
  Home: "첫 화면과 주요 바로가기를 보여줍니다.",
  "Web Installation & Usage": "설치와 개발 적용 방법입니다.",
  "System Installation": "설치 절차와 의존성 버전입니다.",
  "Guide to Web Components": "컴포넌트 사용 기본 규칙입니다.",
  "Web Component Basics": "커스텀 엘리먼트 구조를 이해하고 React/Blade에서 동일하게 사용할 최소 규칙입니다.",
  "Style Customization": "브랜드 컬러, spacing, radius, typography를 토큰으로 바꾸는 허용 범위입니다.",
  "Light DOM Style Considerations": "slot, light DOM, 외부 CSS 영향도를 점검해 예기치 않은 스타일 누수를 막는 기준입니다.",
  "Working with Forms": "입력, 오류, 검증, disabled, required 상태를 폼 컴포넌트와 연결하는 규칙입니다.",
  "Working with LiveView": "서버 렌더링/부분 갱신 화면에서 컴포넌트 상태가 깨지지 않도록 확인하는 기준입니다.",
  "React Components": "React/Vite/Storybook 렌더링 예시입니다.",
  "Next.js SSR": "SSR 환경의 렌더링 기준입니다.",
  "AI Agent Skill": "Codex가 토큰, 컴포넌트, 아이콘 명칭을 읽고 수정할 수 있게 하는 작업 지시서 영역입니다.",
  Changelog: "디자인 토큰과 컴포넌트 변경 이력을 날짜, 작성자, 영향 범위 기준으로 남깁니다.",
  "Migrating From Spark": "기존 Spark 계열 규칙을 신규 보배드림 DS 규칙으로 전환하는 대응표입니다.",
  Typography: "제목, 본문, 가격, 메타, 라벨 텍스트 크기와 줄높이의 기준입니다.",
  "Dimensions/Layout": "컨테이너, 그리드, 카드, 리스트, 상세 화면의 크기와 배치 전환 기준입니다.",
  Lists: "매물 리스트, 링크 목록, 옵션 목록처럼 반복 정보의 행 간격과 구분선을 정의합니다.",
  Buttons: "CTA, 보조 버튼, 아이콘 버튼, 링크 버튼의 높이, radius, 상태값을 정의합니다.",
  "Style Guide": "토큰과 시각 기준을 관리합니다.",
  "Design Tokens": "색상, 글꼴, 간격을 코드 값으로 관리합니다.",
  Installation: "토큰 패키지 설치, import 경로, CSS variables 연결 방식을 기록합니다.",
  Schema: "토큰의 이름, 타입, 값, 설명, 플랫폼 매핑 컬럼 구조를 정의합니다.",
  Color: "브랜드, 본문, 보조 텍스트, 경고, 성공, 구분선 색상을 WCAG 대비와 함께 관리합니다.",
  Font: "폰트 패밀리, 굵기, 숫자 정렬, fallback을 정의합니다.",
  Spacing: "섹션, 카드, 썸네일, 칩, 아이콘과 텍스트 사이의 기본 간격 단위를 정의합니다.",
  Size: "버튼 높이, 아이콘 크기, 터치 타깃, 썸네일 비율 같은 크기 토큰입니다.",
  Elevation: "카드 hover, 드롭다운, 모달, 모바일 하단 고정바의 shadow 레벨입니다.",
  Motion: "hover, active, sheet open, save feedback 등 전환 시간과 easing 기준입니다.",
  Breakpoints: "MO 360/390, tablet 768, PC 1280/1440, wide 1920 기준 반응형 분기점입니다.",
  Icons: "아이콘 이름과 크기 규칙입니다.",
  Forms: "매물 등록/수정, 검색 필터, 문의 폼의 라벨, 도움말, 오류 상태 기준입니다.",
  Imagery: "차량 사진 비율, object-fit, 썸네일 crop, 갤러리, 대체 텍스트 기준입니다.",
  Layout: "PC/MO 컨테이너, 사이드바, sticky filter, 상세 CTA 배치 기준입니다.",
  "Typography & Headings": "H1-H6, 섹션 제목, 가격, 차량명, 메타 텍스트 위계를 정의합니다.",
  "Usability Standards": "찾기 쉬움, 읽기 쉬움, 조작 실수 방지, 모바일 터치성을 점검합니다.",
  "Visual Language": "보배드림의 정보 밀도, 강조 색상, 자동차 거래 신뢰감 표현 기준입니다.",
  Components: "실제 화면에서 조립되는 UI 단위를 Storybook 스토리와 코드 API로 관리합니다.",
  Accordion: "상세 옵션, FAQ, 보험/성능 정보처럼 접고 펼치는 콘텐츠에 사용합니다.",
  Badge: "무사고, 진단, 급매, 인증, 가격인하 같은 상태를 짧게 표시합니다.",
  Breadcrumb: "홈에서 현재 매물/카테고리까지의 정보 구조를 보여주는 탐색 컴포넌트입니다.",
  Button: "주요 CTA, 보조 CTA, outline, ghost, disabled 상태를 관리합니다.",
  Callout: "성능점검, 유의사항, 이벤트, 오류 안내처럼 사용자가 놓치면 안 되는 정보를 강조합니다.",
  "Card Carousel": "추천 매물, 최근 본 매물, 비슷한 차량을 가로 스크롤로 노출합니다.",
  Checkbox: "복수 옵션 선택, 약관 동의, 비교 선택에 사용하는 표준 체크박스입니다.",
  "Checkbox Lite": "밀도 높은 필터 목록에서 간결하게 쓰는 경량 체크박스입니다.",
  Disclaimer: "가격, 보증, 성능점검, 제휴 광고의 법적/운영 고지를 표시합니다.",
  "Feedback Thumbs": "콘텐츠 도움 여부, 상담 품질, 검색 결과 피드백을 빠르게 수집합니다.",
  Fieldset: "제조사, 모델, 가격대, 연식처럼 관련 입력 묶음에 제목과 구조를 제공합니다.",
  Figure: "차량 이미지와 캡션, 출처, 주석을 함께 묶는 미디어 컴포넌트입니다.",
  Filter: "상단 필터, 사이드 필터, 모바일 바텀시트 필터의 공통 동작 기준입니다.",
  "Form Module": "매물 등록/수정 폼의 섹션 단위 묶음과 검증 흐름을 관리합니다.",
  Gallery: "상세 대표 이미지, 스와이프, 전체보기, 영상 진입을 관리합니다.",
  "Gallery Grid": "차량 사진을 여러 장 한 화면에서 비교할 때 쓰는 그리드입니다.",
  "Gallery Thumbnails": "대표 이미지 하단/측면 썸네일 목록과 선택 상태를 정의합니다.",
  Headshot: "딜러, 판매자, 상담원 프로필 사진 표시 기준입니다.",
  Input: "검색어, 가격, 주행거리, 연락처 같은 텍스트 입력의 표준 컴포넌트입니다.",
  "Input Lite": "필터나 테이블 안에서 쓰는 낮은 높이의 경량 입력입니다.",
  Link: "일반 링크, 딜러 페이지 이동, 외부 링크의 색상과 hover 상태를 관리합니다.",
  "Link Pack": "관련 링크 묶음, 푸터 링크, 상세 보조 링크 그룹에 사용합니다.",
  List: "검색 결과, 옵션 정보, 사양 목록 등 반복 행의 간격과 구분선을 정의합니다.",
  Menu: "계정 메뉴, 정렬 메뉴, 더보기 메뉴의 컨테이너입니다.",
  "Menu Item": "메뉴 내부 개별 액션의 높이, 아이콘, disabled 상태를 정의합니다.",
  Modal: "원문에서 취소선 처리된 항목입니다. 신규 구현은 Sheet/Dialog 기준으로 대체 검토합니다.",
  Notification: "저장 완료, 문의 완료, 오류, 가격 변동 알림을 표시합니다.",
  "Page Section": "목록/상세 화면의 큰 섹션 제목, 간격, 배경을 맞추는 레이아웃 단위입니다.",
  Pagination: "검색 결과 페이지 이동, SEO 페이지, 딜러 매물 목록에 사용합니다.",
  "Paging Button": "캐러셀, 갤러리, 페이지 이동에서 이전/다음 조작을 제공합니다.",
  Picker: "차종, 제조사, 지역처럼 한 항목을 고르는 선택 UI입니다.",
  "Picker Option": "Picker 내부 선택 항목의 label, meta, selected 상태입니다.",
  Popover: "정렬, 도움말, 간단 필터처럼 작은 오버레이 콘텐츠를 표시합니다.",
  "Price Range": "원문에서 취소선 처리된 항목입니다. 보배드림은 Range Dual로 우선 통합합니다.",
  "Progress Bar": "사진 업로드, 등록 진행, 비동기 로딩 진행률을 표시합니다.",
  Radio: "단일 선택 옵션을 폼 안에서 명확하게 보여주는 표준 라디오입니다.",
  "Radio Lite": "필터 바텀시트나 고밀도 리스트에서 쓰는 경량 라디오입니다.",
  Range: "가격, 연식, 주행거리 등 단일 범위 입력에 사용합니다.",
  "Range Dual": "가격 최소/최대, 연식 시작/끝처럼 양방향 범위를 조절합니다.",
  Rating: "딜러 평가, 차량 상태, 리뷰 점수를 읽기 전용으로 보여줍니다.",
  "Rating Input": "사용자가 별점/평점을 입력하는 상태와 키보드 조작 기준입니다.",
  Reveal: "접힌 정보 더보기, 옵션 전체보기, 고지문 펼치기에 사용합니다.",
  Save: "찜하기, 저장 매물, 비교 후보 저장의 활성/비활성 상태를 관리합니다.",
  Select: "정렬, 지역, 옵션 선택용 기본 셀렉트입니다.",
  "Select Lite": "테이블/필터 안에서 쓰는 낮은 밀도의 셀렉트입니다.",
  Separator: "매물 카드, 사양 행, 섹션 사이의 시각적 구분선입니다.",
  Spinner: "데이터 로딩 중임을 알리는 최소 피드백 컴포넌트입니다.",
  Stack: "컴포넌트 내부 세로/가로 간격을 일관되게 쌓는 레이아웃 유틸리티입니다.",
  SVG: "아이콘 렌더링, 크기, 색상, 접근성 라벨의 공통 래퍼입니다.",
  Switch: "알림 수신, 판매 옵션 공개 여부처럼 즉시 켜고 끄는 설정에 사용합니다.",
  Tabs: "상세 정보, 성능점검, 보험이력, 리뷰처럼 동등한 콘텐츠 그룹을 전환합니다.",
  Tab: "탭 목록 안의 개별 선택 항목입니다.",
  "Tab Panel": "선택된 탭이 보여주는 콘텐츠 영역과 aria 연결 기준입니다.",
  Textarea: "문의 내용, 설명, 신고 사유처럼 긴 텍스트 입력에 사용합니다.",
  "Textarea Lite": "간단 메모나 고밀도 폼의 경량 긴 텍스트 입력입니다.",
  Tooltip: "아이콘 버튼, 약어, 가격 계산 기준에 짧은 도움말을 제공합니다.",
  "plop:component": "새 컴포넌트 문서가 생성될 때 자동 삽입되는 자리입니다.",
  Principles: "보배드림 디자인 의사결정의 상위 원칙과 모션 원칙을 모읍니다.",
  "Design Principles": "신뢰, 빠른 비교, 명확한 거래 행동을 우선하는 설계 원칙입니다.",
  "Motion Principles": "과장되지 않은 피드백, 위치 변화, sheet 전환, 저장 애니메이션 원칙입니다.",
  "Content Strategy": "버튼명, 필터명, 고지문, 오류문구의 말투와 작성 기준을 관리합니다.",
  "Content Strategy Principles": "콘텐츠가 짧고 명확하며 거래 리스크를 줄이는 방향으로 쓰이게 합니다.",
  "Voice and Tone": "보배드림의 신뢰감 있는 말투, 안내/경고/성공 상태의 톤을 정의합니다.",
  "Grammar and Mechanics": "띄어쓰기, 숫자/단위 표기, 가격 표기, 문장 부호 규칙입니다.",
  Vocabulary: "제조사, 모델, 트림, 사고, 진단, 금융 등 서비스 용어 사전입니다.",
  Accessibility: "누구나 탐색하고 문의할 수 있게 하는 기준입니다.",
  "Accessibility Principles": "장애 여부와 입력 장치와 관계없이 매물 탐색과 문의가 가능해야 한다는 원칙입니다.",
  "Accessibility Checklist": "개발/QA가 화면마다 체크하는 접근성 항목 목록입니다.",
  "Global Code": "전체 HTML 구조, landmarks, aria 사용의 기본 품질 기준입니다.",
  "Default Language": "문서 기본 언어를 ko로 선언해 스크린리더 발음을 안정화합니다.",
  "Semantic HTML": "버튼은 button, 링크는 a, 목록은 list로 구현하는 기본 원칙입니다.",
  "Unique Page Title Element": "각 페이지가 고유한 title을 가져 현재 위치를 이해할 수 있게 합니다.",
  "Keyboard Navigation": "마우스 없이 주요 탐색, 필터, 저장, 문의 조작이 가능해야 합니다.",
  "Focus State": "포커스 위치가 모든 배경에서 충분히 보이도록 스타일을 정의합니다.",
  "Keyboard Interaction": "컴포넌트별 Enter, Space, Escape, Arrow 키 동작을 명시합니다.",
  "Logical Tab Order": "화면 시각 순서와 키보드 이동 순서가 자연스럽게 일치해야 합니다.",
  "Minimum Contrast Ratio": "텍스트와 UI 컴포넌트의 최소 대비 기준을 검수합니다.",
  "Text Contrast": "가격, 메타, disabled, 오류 문구의 대비를 별도로 확인합니다.",
  "Multi Device Responsive Design": "PC, 태블릿, 모바일에서 내용이 겹치거나 잘리지 않는지 확인합니다.",
  "Text Resizing": "사용자가 글자를 키워도 CTA, 필터, 카드가 깨지지 않도록 합니다.",
  "Touch Targets": "모바일 터치 영역은 최소 44px 수준으로 유지합니다.",
  "Moving, Flashing, or Blinking Content": "움직이거나 깜빡이는 콘텐츠가 사용자를 방해하지 않도록 제한합니다.",
  "Content Flash": "광과민 위험이 있는 빠른 깜빡임을 금지합니다.",
  "Stop Motion": "자동 재생, carousel, 영상에는 정지/제어 방법을 제공합니다.",
  Headings: "페이지 제목과 섹션 제목의 문서 구조를 관리합니다.",
  "Clear Headings": "제목만 보고도 섹션 목적과 현재 맥락을 이해할 수 있게 합니다.",
  "Sequential Headings": "h1부터 순차적으로 heading level을 사용합니다.",
  "Forms, Labels, and Errors": "폼 라벨, 도움말, 오류 연결을 스크린리더 기준으로 점검합니다.",
  "Form Errors": "오류 위치, 원인, 해결 방법이 입력 항목과 연결되어야 합니다.",
  "Form Labels": "모든 입력에는 보이는 라벨 또는 접근 가능한 이름이 있어야 합니다.",
  "Forms Keyboard Accessible": "폼 입력, 선택, 제출이 키보드만으로 가능해야 합니다.",
  "Written Material (Copy)": "문구가 짧고 명확하며 전문 용어는 필요한 곳에만 사용되는지 점검합니다.",
  "Clear Content": "사용자가 거래 판단에 필요한 정보를 빠르게 이해할 수 있게 씁니다.",
  "Meaningful Link Text": "링크 텍스트만으로 이동 목적을 알 수 있어야 합니다.",
  "Image Text Alternatives": "이미지 의미를 전달하는 대체 텍스트 정책을 관리합니다.",
  "Image Alt Text": "차량 사진, 아이콘, 배지 이미지의 alt 규칙을 정의합니다.",
  "Color Contrast": "색상 조합별 대비 수치를 기록하고 실패 조합은 사용 금지합니다.",
  Resources: "디자인/개발/QA가 함께 참고하는 외부 도구와 운영 자료를 모읍니다.",
  Toolbox: "측정 도구, 접근성 도구, Storybook/Chromatic 운영 링크를 등록합니다.",
};

const itemStatus = (label: string): CatalogStatus => referenceStatus[label] ?? (requiredLabels.has(label) ? "필수" : "권장");

const catalogItem = (label: string, parent?: string): CatalogItem => ({
  label,
  korean: koreanNames[label],
  parent,
  note:
    fuseNotes[label] ??
    `${parent ? `${parent}에서 쓰는 ` : ""}보배드림 UI 항목입니다.`,
  status: itemStatus(label),
});

const catalogItems = (items: CatalogInput[]) =>
  items.map((entry) => (Array.isArray(entry) ? catalogItem(entry[0], entry[1]) : catalogItem(entry)));

const marketplaceItem = (label: string, note: string, status: CatalogStatus = "권장", parent?: string): CatalogItem => ({
  label,
  korean: koreanNames[label],
  note,
  parent,
  status,
});

const slugifySidebarSegment = (value: string) =>
  value
    .replace(/~~/g, "")
    .replace(/&/g, " and ")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const sidebarNode = (entry: SidebarInput, trail: string[] = [], depth = 0): SidebarNode => {
  const config = typeof entry === "string" ? { title: entry } : entry;
  const path = [...trail, config.title];
  const id = path.map(slugifySidebarSegment).filter(Boolean).join("-");
  const status = config.status ?? (referenceStatus[config.title] === "보류" ? "deprecated" : "stable");
  const children = config.children?.map((child) => sidebarNode(child, path, depth + 1));

  return {
    id,
    title: config.title,
    koTitle: koreanNames[config.title] ?? config.title,
    href: config.href ?? `#${id}`,
    depth,
    status,
    children,
  };
};

const sidebarTree = (entries: SidebarInput[]) => entries.map((entry) => sidebarNode(entry));

const customSidebarItem = (title: string, href?: string, children?: SidebarInput[]): SidebarInput => ({
  title,
  href,
  status: "custom",
  children,
});

export const fuseSidebarTree: SidebarNode[] = sidebarTree([
  "Home",
  {
    title: "Web Installation & Usage",
    children: [
      "System Installation",
      {
        title: "Guide to Web Components",
        children: [
          "Web Component Basics",
          "Style Customization",
          "Light DOM Style Considerations",
          "Working with Forms",
          "Working with LiveView",
        ],
      },
      "React Components",
      "Next.js SSR",
      "AI Agent Skill",
      "Changelog",
      {
        title: "Migrating From Spark",
        children: ["Design Tokens", "Typography", "Forms", "Dimensions/Layout", "Lists", "Buttons"],
      },
    ],
  },
  {
    title: "Style Guide",
    children: [
      {
        title: "Design Tokens",
        children: ["Installation", "Schema", "Color", "Font", "Spacing", "Size", "Elevation", "Motion", "Breakpoints"],
      },
      {
        title: "Foundations",
        children: [
          "Design Token",
          "Color",
          "Typography",
          "Iconography",
          "Elevation",
          "Gradient",
          "Inclusive Design",
          "International Design",
          "Layout",
          "Motion",
          "Radius",
          "Spacing",
          "State",
          "Voice and Tone",
          "Writing",
          "Feedback",
        ],
      },
      "Forms",
      "Imagery",
      "Layout",
      "Spacing",
      "Typography & Headings",
      "Usability Standards",
      "Visual Language",
    ],
  },
  {
    title: "Icons",
    href: "#style-guide-icons",
    children: [
      { title: "UI Icons", href: "#style-guide-icons-ui-icons" },
      { title: "Frequent Icons", href: "#style-guide-icons-frequent-icons" },
      { title: "Option Icons", href: "#style-guide-icons-option-icons" },
      { title: "Vehicle Info Icons", href: "#style-guide-icons-vehicle-info-icons" },
      { title: "Brand Icons", href: "#style-guide-icons-brand-icons" },
      { title: "Community Icons", href: "#style-guide-icons-community-icons" },
    ],
  },
  {
    title: "Components",
    children: [
      "Accordion",
      "Badge",
      "Breadcrumb",
      "Button",
      "Callout",
      "Card",
      "Card Carousel",
      "Checkbox",
      "Checkbox Lite",
      "Disclaimer",
      "Feedback Thumbs",
      "Fieldset",
      "Figure",
      "Filter",
      "Form Module",
      "Gallery",
      "Gallery Grid",
      "Gallery Thumbnails",
      "Headshot",
      "Input",
      "Input Lite",
      "Link",
      "Link Pack",
      "List",
      "Menu",
      "Menu Item",
      { title: "Modal", status: "deprecated" },
      "Notification",
      "Page Section",
      "Pagination",
      "Paging Button",
      "Picker",
      "Picker Option",
      "Popover",
      { title: "Price Range", status: "deprecated" },
      "Progress Bar",
      "Radio",
      "Radio Lite",
      "Range",
      "Range Dual",
      "Rating",
      "Rating Input",
      "Reveal",
      "Save",
      "Select",
      "Select Lite",
      "Separator",
      "Spinner",
      "Stack",
      "SVG",
      "Switch",
      "Tabs",
      "Tab",
      "Tab Panel",
      "Textarea",
      "Textarea Lite",
      "Tooltip",
      {
        title: "Mobile/App Components",
        children: [
          "Action Button",
          "Alert Dialog",
          "Attachment Input",
          "Avatar",
          "Bottom Navigation",
          "Bottom Sheet",
          "Chip",
          "Content Placeholder",
          "Contextual Floating Button",
          "Date Picker",
          "Dialog",
          "Divider",
          "Field",
          "Floating Action Button",
          "Footer",
          "Help Bubble",
          "Identity Placeholder",
          "Image Frame",
          "Input Button",
          "Manner Temp & Manner Temp Badge",
          "Menu Sheet",
          "Notification Badge",
          "Page Banner",
          "Progress Circle",
          "Quantity Picker",
          "Reaction Button",
          "Result Section",
          "Scroll Fog",
          "Segmented Control",
          "Select Box",
          "Side Navigation",
          "Side Panel",
          "Skeleton",
          "Slider",
          "Table Pagination",
          "Tag Group",
          "Text Input & Textarea",
          "Time Picker",
          "Top Navigation",
          "Wheel Picker",
        ],
      },
    ],
  },
  {
    title: "Patterns",
    children: [
      "Bulk editing",
      "Creating forms",
      "Empty states",
      "Filtering",
      "Loading",
      "Requesting user feedback",
      "Uploading files",
      "Using links",
      "Text link",
      "Legal link",
    ],
  },
  {
    title: "Principles",
    children: ["Design Principles", "Motion Principles"],
  },
  {
    title: "Content Strategy",
    children: ["Content Strategy Principles", "Voice and Tone", "Grammar and Mechanics", "Vocabulary"],
  },
  {
    title: "Accessibility",
    children: [
      "Accessibility Principles",
      {
        title: "Accessibility Checklist",
        children: [
          "Global Code",
          "Default Language",
          "Semantic HTML",
          "Unique Page Title Element",
          "Keyboard Navigation",
          "Focus State",
          "Keyboard Interaction",
          "Logical Tab Order",
          "Minimum Contrast Ratio",
          "Text Contrast",
          "Multi Device Responsive Design",
          "Text Resizing",
          "Touch Targets",
          "Moving, Flashing, or Blinking Content",
          "Content Flash",
          "Stop Motion",
          "Headings",
          "Clear Headings",
          "Sequential Headings",
          "Forms, Labels, and Errors",
          "Form Errors",
          "Form Labels",
          "Forms Keyboard Accessible",
          "Written Material (Copy)",
          "Clear Content",
          "Meaningful Link Text",
          "Image Text Alternatives",
          "Image Alt Text",
        ],
      },
      "Color Contrast",
    ],
  },
  {
    title: "Resources",
    children: [
      "Toolbox",
      "References",
      "Coverage Matrix",
      {
        title: "Cars.com Cross-check",
        children: ["Component IA", "Naming Gaps", "Migration Order"],
      },
      "Storybook",
      "QA Checklist",
      {
        title: "Bootstrap Cross-check",
        children: ["Getting Started", "Customize", "Layout", "Content", "Forms", "Components", "Helpers", "Utilities"],
      },
      customSidebarItem("보배드림 운영", "#registry", [
        customSidebarItem("컴포넌트 등록/수정", "#registry"),
        customSidebarItem("측정 마스터", "#workflow"),
        customSidebarItem("매물 목록 패턴", "#component-showcase"),
        customSidebarItem("매물 상세 패턴", "#preview"),
        customSidebarItem("필터 패턴", "#preview"),
        customSidebarItem("AI 측정 흐름", "#workflow"),
      ]),
    ],
  },
]);

export const bobaedreamUseCases: Record<string, string[]> = {
  Filter: ["연식, 주행거리, 가격, 지역, 제조사 필터", "PC 사이드 필터와 모바일 바텀시트 필터", "선택 조건 칩과 결과 수 동기화"],
  Card: ["매물 카드", "리스트형/갤러리형/추천 매물 카드", "썸네일, 가격, 신뢰 배지, 판매자 메타 조합"],
  Gallery: ["차량 사진 영역", "상세 대표 이미지와 썸네일 rail", "동영상 진입, 전체보기, 사진 개수 표시"],
  Badge: ["무사고, 진단, 급매, 실매물", "가격인하, 브랜드인증, 판매완료 상태", "카드와 상세 상단의 신뢰 신호"],
  Save: ["찜 버튼", "매물 카드/상세 상단/하단 CTA 저장 상태", "저장 완료 알림과 active 피드백"],
  Pagination: ["매물 리스트 페이지 이동", "SEO 페이지네이션과 이전/다음 버튼", "모바일 더보기 전환 기준"],
  "Range Dual": ["가격/주행거리 범위 선택", "연식 시작/끝 선택", "바텀시트 내 최소/최대 입력 동기화"],
  Tabs: ["상세정보, 성능점검, 보험이력", "딜러 정보와 리뷰 전환", "sticky anchor tab과 aria 연결"],
  Notification: ["견적/문의/오류 알림", "찜 저장 완료와 가격 변동 안내", "등록 폼 검증 결과 피드백"],
  "보배드림 운영": ["컴포넌트 등록/수정", "측정 마스터 관리", "AI 측정 워크플로우 운영"],
};

export const referenceSystems = [
  {
    name: "자동차 UI 레퍼런스",
    role: "자동차 UI 목차",
    url: "https://www.autotrader.com/",
    apply: "문서 구조와 컴포넌트 분류",
  },
  {
    name: "eBay Playbook",
    role: "마켓플레이스 UI",
    url: "https://playbook.ebay.com/design-system/components",
    apply: "토큰, 컴포넌트, 패턴 분류",
  },
  {
    name: "Seed Design",
    role: "간결한 한국어 설명",
    url: "https://seed-design.io/",
    apply: "한 문장 정의와 표 문구",
  },
  {
    name: "Bootstrap",
    role: "대표 UI 키트 구조",
    url: "https://getbootstrap.com/docs/5.3/getting-started/introduction/",
    apply: "설치, 커스터마이즈, 레이아웃, 폼, 컴포넌트, 헬퍼, 유틸리티 축 검토",
  },
  {
    name: "Storybook",
    role: "컴포넌트 실물 뷰어",
    url: "https://storybook.js.org/",
    apply: "상태별 화면, 반응형, 접근성, 개발 QA",
  },
  {
    name: "Chromatic",
    role: "화면 변경 승인",
    url: "https://www.chromatic.com/",
    apply: "시각 회귀 테스트, PR 리뷰, 승인 이력",
  },
];

export const fuseGroups: CatalogGroup[] = [
  {
    group: "Home",
    description: "첫 화면",
    items: catalogItems(["Home"]),
  },
  {
    group: "Web Installation & Usage",
    description: "설치와 개발 적용",
    items: catalogItems([
      "Web Installation & Usage",
      ["System Installation", "Web Installation & Usage"],
      ["Guide to Web Components", "Web Installation & Usage"],
      ["Web Component Basics", "Guide to Web Components"],
      ["Style Customization", "Guide to Web Components"],
      ["Light DOM Style Considerations", "Guide to Web Components"],
      ["Working with Forms", "Guide to Web Components"],
      ["Working with LiveView", "Guide to Web Components"],
      ["React Components", "Web Installation & Usage"],
      ["Next.js SSR", "Web Installation & Usage"],
      ["AI Agent Skill", "Web Installation & Usage"],
      ["Changelog", "Web Installation & Usage"],
      ["Migrating From Spark", "Web Installation & Usage"],
      ["Design Tokens", "Migrating From Spark"],
      ["Typography", "Migrating From Spark"],
      ["Forms", "Migrating From Spark"],
      ["Dimensions/Layout", "Migrating From Spark"],
      ["Lists", "Migrating From Spark"],
      ["Buttons", "Migrating From Spark"],
    ]),
  },
  {
    group: "Style Guide",
    description: "토큰과 시각 기준",
    items: catalogItems([
      "Style Guide",
      ["Design Tokens", "Style Guide"],
      ["Installation", "Design Tokens"],
      ["Schema", "Design Tokens"],
      ["Color", "Design Tokens"],
      ["Font", "Design Tokens"],
      ["Spacing", "Design Tokens"],
      ["Size", "Design Tokens"],
      ["Elevation", "Design Tokens"],
      ["Motion", "Design Tokens"],
      ["Breakpoints", "Design Tokens"],
      ["Icons", "Style Guide"],
      ["Forms", "Style Guide"],
      ["Imagery", "Style Guide"],
      ["Layout", "Style Guide"],
      ["Spacing", "Style Guide"],
      ["Typography & Headings", "Style Guide"],
      ["Usability Standards", "Style Guide"],
      ["Visual Language", "Style Guide"],
    ]),
  },
  {
    group: "Components",
    description: "컴포넌트 목록",
    items: catalogItems([
      "Components",
      ["Accordion", "Components"],
      ["Badge", "Components"],
      ["Breadcrumb", "Components"],
      ["Button", "Components"],
      ["Callout", "Components"],
      ["Card", "Components"],
      ["Card Carousel", "Components"],
      ["Checkbox", "Components"],
      ["Checkbox Lite", "Components"],
      ["Disclaimer", "Components"],
      ["Feedback Thumbs", "Components"],
      ["Fieldset", "Components"],
      ["Figure", "Components"],
      ["Filter", "Components"],
      ["Form Module", "Components"],
      ["Gallery", "Components"],
      ["Gallery Grid", "Components"],
      ["Gallery Thumbnails", "Components"],
      ["Headshot", "Components"],
      ["Input", "Components"],
      ["Input Lite", "Components"],
      ["Link", "Components"],
      ["Link Pack", "Components"],
      ["List", "Components"],
      ["Menu", "Components"],
      ["Menu Item", "Components"],
      ["Modal", "Components"],
      ["Notification", "Components"],
      ["Page Section", "Components"],
      ["Pagination", "Components"],
      ["Paging Button", "Components"],
      ["Picker", "Components"],
      ["Picker Option", "Components"],
      ["Popover", "Components"],
      ["Price Range", "Components"],
      ["Progress Bar", "Components"],
      ["Radio", "Components"],
      ["Radio Lite", "Components"],
      ["Range", "Components"],
      ["Range Dual", "Components"],
      ["Rating", "Components"],
      ["Rating Input", "Components"],
      ["Reveal", "Components"],
      ["Save", "Components"],
      ["Select", "Components"],
      ["Select Lite", "Components"],
      ["Separator", "Components"],
      ["Spinner", "Components"],
      ["Stack", "Components"],
      ["SVG", "Components"],
      ["Switch", "Components"],
      ["Tabs", "Components"],
      ["Tab", "Components"],
      ["Tab Panel", "Components"],
      ["Textarea", "Components"],
      ["Textarea Lite", "Components"],
      ["Tooltip", "Components"],
      ["plop:component", "Components"],
    ]),
  },
  {
    group: "Principles",
    description: "원칙",
    items: catalogItems(["Principles", ["Design Principles", "Principles"], ["Motion Principles", "Principles"]]),
  },
  {
    group: "Content Strategy",
    description: "문구와 용어",
    items: catalogItems([
      "Content Strategy",
      ["Content Strategy Principles", "Content Strategy"],
      ["Voice and Tone", "Content Strategy"],
      ["Grammar and Mechanics", "Content Strategy"],
      ["Vocabulary", "Content Strategy"],
    ]),
  },
  {
    group: "Accessibility",
    description: "접근성 기준",
    items: catalogItems([
      "Accessibility",
      ["Accessibility Principles", "Accessibility"],
      ["Accessibility Checklist", "Accessibility"],
      ["Global Code", "Accessibility Checklist"],
      ["Default Language", "Accessibility Checklist"],
      ["Semantic HTML", "Accessibility Checklist"],
      ["Unique Page Title Element", "Accessibility Checklist"],
      ["Keyboard Navigation", "Accessibility Checklist"],
      ["Focus State", "Accessibility Checklist"],
      ["Keyboard Interaction", "Accessibility Checklist"],
      ["Logical Tab Order", "Accessibility Checklist"],
      ["Minimum Contrast Ratio", "Accessibility Checklist"],
      ["Text Contrast", "Accessibility Checklist"],
      ["Multi Device Responsive Design", "Accessibility Checklist"],
      ["Text Resizing", "Accessibility Checklist"],
      ["Touch Targets", "Accessibility Checklist"],
      ["Moving, Flashing, or Blinking Content", "Accessibility Checklist"],
      ["Content Flash", "Accessibility Checklist"],
      ["Stop Motion", "Accessibility Checklist"],
      ["Headings", "Accessibility Checklist"],
      ["Clear Headings", "Accessibility Checklist"],
      ["Sequential Headings", "Accessibility Checklist"],
      ["Forms, Labels, and Errors", "Accessibility Checklist"],
      ["Form Errors", "Accessibility Checklist"],
      ["Form Labels", "Accessibility Checklist"],
      ["Forms Keyboard Accessible", "Accessibility Checklist"],
      ["Written Material (Copy)", "Accessibility Checklist"],
      ["Clear Content", "Accessibility Checklist"],
      ["Meaningful Link Text", "Accessibility Checklist"],
      ["Image Text Alternatives", "Accessibility Checklist"],
      ["Image Alt Text", "Accessibility Checklist"],
      ["Color Contrast", "Accessibility"],
    ]),
  },
  {
    group: "Resources",
    description: "도구",
    items: catalogItems(["Resources", ["Toolbox", "Resources"]]),
  },
];

export const ebayGroups: CatalogGroup[] = [
  {
    group: "Design System",
    description: "상위 구조",
    items: [
      marketplaceItem("Overview", "보배드림 DS 첫 화면과 운영 목적을 설명합니다.", "필수"),
      marketplaceItem("Principles", "마켓플레이스 UX 의사결정 기준을 보배드림 원칙으로 변환합니다.", "필수"),
      marketplaceItem("Tokens", "색상, spacing, typography, motion 등 코드 변수 체계를 관리합니다.", "필수"),
      marketplaceItem("Components", "실제 화면에 들어가는 컴포넌트를 Storybook 스토리로 관리합니다.", "필수"),
      marketplaceItem("Patterns", "필터링, 빈 상태, 폼 작성처럼 화면 흐름 단위 기준을 정리합니다.", "필수"),
      marketplaceItem("Processes", "등록, 검수, 승인, 배포 운영 프로세스를 정의합니다.", "권장"),
      marketplaceItem("Change log", "컴포넌트/토큰 변경 이력을 남깁니다.", "필수"),
    ],
  },
  {
    group: "Tokens",
    description: "토큰 분류",
    items: [
      "Overview",
      "Change log",
      "Theming",
      "Color",
      "Dimension",
      "Spacing",
      "Typography",
      "Breakpoints",
      "Shadow",
      "Shape",
      "Opacity",
      "Motion",
      "Illustration",
    ].map((label) =>
      marketplaceItem(label, "보배드림 CSS 변수, Figma Variables, Laravel Blade 클래스명과 매핑합니다.", "필수"),
    ),
  },
  {
    group: "Components",
    description: "컴포넌트 분류",
    items: [
      marketplaceItem("Overview", "컴포넌트 문서 작성 방식과 상태 표기 기준입니다.", "필수"),
      marketplaceItem("Status", "컴포넌트 사용 가능/보류/폐기 상태를 표시합니다.", "필수"),
      marketplaceItem("Accordion", "접힘/펼침 정보 영역입니다.", "권장"),
      marketplaceItem("Action bar", "모바일 하단 문의/찜/공유 고정 영역입니다.", "필수"),
      marketplaceItem("Alert notice", "경고/안내 notice 체계입니다.", "필수"),
      marketplaceItem("Inline notice", "입력 필드나 카드 안쪽의 짧은 안내입니다.", "필수", "Alert notice"),
      marketplaceItem("Page notice", "페이지 상단 전체 안내입니다.", "권장", "Alert notice"),
      marketplaceItem("Section notice", "섹션 단위 안내입니다.", "권장", "Alert notice"),
      marketplaceItem("Avatar", "판매자/딜러 프로필 이미지입니다.", "권장"),
      marketplaceItem("Badge", "매물 상태와 신뢰 신호를 표시합니다.", "필수"),
      marketplaceItem("Banner", "프로모션, 공지, 이벤트 노출 영역입니다.", "권장"),
      marketplaceItem("Breadcrumb", "카테고리 경로 탐색입니다.", "필수"),
      marketplaceItem("Buttons", "버튼 체계의 상위 문서입니다.", "필수"),
      marketplaceItem("CTA button", "문의, 매물 등록, 상담 신청 같은 핵심 버튼입니다.", "필수", "Buttons"),
      marketplaceItem("Icon button", "찜, 공유, 닫기 같은 아이콘 중심 버튼입니다.", "필수", "Buttons"),
      marketplaceItem("Link button", "링크처럼 보이지만 버튼 동작을 하는 액션입니다.", "권장", "Buttons"),
      marketplaceItem("Calendar", "날짜 선택과 예약 흐름입니다.", "권장"),
      marketplaceItem("Card", "매물 카드와 정보 카드입니다.", "필수"),
      marketplaceItem("Carousel", "추천 매물과 이미지 묶음 탐색입니다.", "필수"),
      marketplaceItem("CCD", "eBay 공개 항목을 대응 보류 항목으로 기록합니다.", "보류"),
      marketplaceItem("Chip", "필터/선택/입력 칩 체계입니다.", "필수"),
      marketplaceItem("Filter chip", "조건 필터 선택 상태를 보여줍니다.", "필수", "Chip"),
      marketplaceItem("Input chip", "사용자가 입력한 조건을 칩으로 보여줍니다.", "필수", "Chip"),
      marketplaceItem("Data visualization", "가격 추이, 통계, 성능 점검 지표를 시각화합니다.", "권장"),
      marketplaceItem("Graphs", "시세 그래프와 데이터 차트입니다.", "권장", "Data visualization"),
      marketplaceItem("Metrics", "조회수, 찜 수, 가격 변동 같은 핵심 수치입니다.", "권장", "Data visualization"),
      marketplaceItem("Dialog", "확인, 경고, 표준 모달 대화 상자입니다.", "필수"),
      marketplaceItem("Alert", "위험하거나 되돌리기 어려운 행동 경고입니다.", "필수", "Dialog"),
      marketplaceItem("Confirmation", "삭제/저장/문의 전 확인입니다.", "필수", "Dialog"),
      marketplaceItem("Standard", "일반 정보 입력/확인 대화 상자입니다.", "권장", "Dialog"),
      marketplaceItem("Divider", "섹션과 행 구분선입니다.", "필수"),
      marketplaceItem("Education notice", "기능 사용법과 정책 안내입니다.", "권장"),
      marketplaceItem("EEK rating and range", "등급/범위형 평가 UI입니다.", "권장"),
      marketplaceItem("Expansion", "더보기/접기 콘텐츠입니다.", "권장"),
      marketplaceItem("Input", "입력 컴포넌트 상위 분류입니다.", "필수"),
      marketplaceItem("Checkbox", "복수 선택입니다.", "필수", "Input"),
      marketplaceItem("Combobox", "검색 가능한 선택 입력입니다.", "필수", "Input"),
      marketplaceItem("Date field", "날짜 입력입니다.", "권장", "Input"),
      marketplaceItem("Dropdown", "드롭다운 메뉴/선택입니다.", "필수", "Input"),
      marketplaceItem("Numeric stepper", "가격/연식/수량 숫자 증감입니다.", "필수", "Input"),
      marketplaceItem("Password", "계정 보안 입력입니다.", "권장", "Input"),
      marketplaceItem("Phone number", "전화번호 입력입니다.", "필수", "Input"),
      marketplaceItem("Radio button", "단일 선택입니다.", "필수", "Input"),
      marketplaceItem("Select list", "선택 목록입니다.", "필수", "Input"),
      marketplaceItem("Switch", "설정 켜기/끄기입니다.", "필수", "Input"),
      marketplaceItem("Text area", "긴 텍스트 입력입니다.", "필수", "Input"),
      marketplaceItem("Text field", "기본 텍스트 입력입니다.", "필수", "Input"),
      marketplaceItem("Item tile", "상품/매물 타일입니다.", "필수"),
      marketplaceItem("List row", "리스트형 매물 행입니다.", "필수"),
      marketplaceItem("Loading", "로딩 상태 상위 분류입니다.", "필수"),
      marketplaceItem("Expressive loader", "브랜드성이 있는 로딩 피드백입니다.", "권장", "Loading"),
      marketplaceItem("Skeleton loader", "리스트/상세 데이터 로딩 자리 표시자입니다.", "필수", "Loading"),
      marketplaceItem("Media container", "이미지/영상 컨테이너입니다.", "필수"),
      marketplaceItem("Navigation", "상단/하단 탐색 구조입니다.", "필수"),
      marketplaceItem("Top navigation bar", "PC/MO 주요 내비게이션 바입니다.", "필수", "Navigation"),
      marketplaceItem("Pagination", "페이지 이동입니다.", "필수"),
      marketplaceItem("Panel", "사이드 패널과 정보 패널입니다.", "권장"),
      marketplaceItem("Popover", "작은 오버레이 안내와 메뉴입니다.", "필수"),
      marketplaceItem("Progress stepper", "매물 등록 단계 진행 표시입니다.", "필수"),
      marketplaceItem("Search field", "검색 입력과 자동완성입니다.", "필수"),
      marketplaceItem("Section header", "섹션 제목과 보조 액션 영역입니다.", "필수"),
      marketplaceItem("Segmented button", "보기 방식/조건 전환 버튼 그룹입니다.", "권장"),
      marketplaceItem("Sheet", "모바일 바텀시트와 포커스 시트입니다.", "필수"),
      marketplaceItem("Context sheet", "필터, 정렬, 공유처럼 맥락 기반 sheet입니다.", "필수", "Sheet"),
      marketplaceItem("Focus sheet", "입력이나 선택에 집중하는 sheet입니다.", "권장", "Sheet"),
      marketplaceItem("Signal", "상태 신호, 신뢰 배지, 시스템 상태 표시입니다.", "권장"),
      marketplaceItem("Snackbar", "짧은 성공/실패 피드백입니다.", "필수"),
      marketplaceItem("State layer", "hover, pressed, selected 상태 레이어입니다.", "필수"),
      marketplaceItem("Tab", "탭 탐색입니다.", "필수"),
      marketplaceItem("Table", "관리자/비교표 데이터 테이블입니다.", "권장"),
      marketplaceItem("Tip", "짧은 도움말 체계입니다.", "권장"),
      marketplaceItem("Tooltip", "마우스/포커스 도움말입니다.", "권장", "Tip"),
      marketplaceItem("Tourtip", "신규 기능 안내용 단계 도움말입니다.", "권장", "Tip"),
      marketplaceItem("Toggle button group", "상태 전환 버튼 묶음입니다.", "권장"),
      marketplaceItem("Video player", "차량 영상과 숏폼 재생기입니다.", "필수"),
    ],
  },
  {
    group: "Patterns",
    description: "패턴 분류",
    items: [
      marketplaceItem("Overview", "패턴 문서의 구조와 적용 원칙입니다.", "필수"),
      marketplaceItem("Bulk editing", "관리자 옵션/아이콘 일괄 수정입니다.", "권장"),
      marketplaceItem("Creating forms", "매물 등록/수정 폼 작성 흐름입니다.", "필수"),
      marketplaceItem("Empty states", "검색 결과 없음, 저장 매물 없음, 오류 복구 화면입니다.", "필수"),
      marketplaceItem("Filtering", "차량 조건 필터, 칩, 바텀시트, 결과 수 반영입니다.", "필수"),
      marketplaceItem("Requesting user feedback", "신고, 문의, 검수 피드백 수집입니다.", "권장"),
      marketplaceItem("Uploading files", "차량 사진/숏폼 영상 업로드입니다.", "필수"),
      marketplaceItem("Using links", "서비스 내부/외부/법적 링크 사용 기준입니다.", "권장"),
      marketplaceItem("Text link", "본문 안 링크 스타일입니다.", "권장", "Using links"),
      marketplaceItem("Legal link", "약관/정책/법적 고지 링크입니다.", "필수", "Using links"),
    ],
  },
];

export const bobaedreamTokens: Token[] = [
  { name: "--bd-color-brand", value: "#d71920", korean: "브랜드 레드", usage: "주요 CTA, 활성 상태, 알림 강조" },
  { name: "--bd-color-ink", value: "#111827", korean: "본문 검정", usage: "차량명, 가격, 핵심 정보" },
  { name: "--bd-color-muted", value: "#6b7280", korean: "보조 텍스트", usage: "연식, 주행거리, 지역, 딜러 메타" },
  { name: "--bd-color-line", value: "#e5e7eb", korean: "구분선", usage: "매물 카드, 테이블, 섹션 분리" },
  { name: "--bd-space-4", value: "4px", korean: "간격 4", usage: "아이콘과 텍스트 사이, 가격과 단위 사이" },
  { name: "--bd-space-8", value: "8px", korean: "간격 8", usage: "칩 사이, 작은 버튼 내부, 썸네일 안쪽 여백" },
  { name: "--bd-space-10", value: "10px", korean: "간격 10", usage: "컴팩트 카드 행, 작은 입력 보조 영역" },
  { name: "--bd-space-12", value: "12px", korean: "간격 12", usage: "매물 카드 내부, 필터 레일, 입력 묶음" },
  { name: "--bd-space-14", value: "14px", korean: "간격 14", usage: "모바일 리스트 보조 간격, 좁은 카드 padding" },
  { name: "--bd-space-16", value: "16px", korean: "간격 16", usage: "기본 스택 간격, 폼 필드 사이, 카드 묶음" },
  { name: "--bd-space-18", value: "18px", korean: "간격 18", usage: "PC 카드 내부 여백, 섹션 안쪽 보조 간격" },
  { name: "--bd-space-20", value: "20px", korean: "간격 20", usage: "모바일 화면 좌우 여백, 리스트 블록 간격" },
  { name: "--bd-space-24", value: "24px", korean: "간격 24", usage: "섹션 내부 그룹, 상세 정보 블록 상하 간격" },
  { name: "--bd-space-32", value: "32px", korean: "간격 32", usage: "문서 섹션, PC 콘텐츠 그룹 사이" },
  { name: "--bd-space-40", value: "40px", korean: "간격 40", usage: "큰 화면 섹션 상하 여백, 주요 카드 그룹" },
  { name: "--bd-space-48", value: "48px", korean: "간격 48", usage: "페이지 블록 분리, 문서 상단 여백" },
  { name: "--bd-space-56", value: "56px", korean: "간격 56", usage: "넓은 화면 주요 섹션 간격" },
  { name: "--bd-space-64", value: "64px", korean: "간격 64", usage: "PC 최상위 페이지 섹션 분리" },
  { name: "--bd-space-gap", value: "16px", korean: "기본 스택 간격", usage: "카드 목록, 폼 행, 반복 요소의 기본 gap" },
  { name: "--bd-radius-card", value: "8px", korean: "카드 모서리", usage: "매물 카드, 입력 패널" },
  { name: "--bd-radius-chip", value: "999px", korean: "칩 모서리", usage: "필터 칩, 상태 배지" },
  { name: "--bd-shadow-sticky", value: "0 -2px 14px rgba(17,24,39,.12)", korean: "고정 바 그림자", usage: "모바일 하단 문의 바" },
  { name: "--bd-z-sticky", value: "100", korean: "고정 영역 계층", usage: "필터 바, 하단 CTA" },
];

export const iconLibraries = [
  {
    library: "interface",
    korean: "인터페이스",
    source: "보배드림 기본 아이콘",
    icons: [
      { name: "ic_interface_search_24", korean: "검색", size: "24px", usage: "검색창, 제조사 검색" },
      { name: "ic_interface_filter_24", korean: "필터", size: "24px", usage: "상단 필터, 조건 개수 표시" },
      { name: "ic_interface_chevron_16", korean: "화살표", size: "16px", usage: "Breadcrumb, 펼침, 이동" },
      { name: "ic_interface_close_24", korean: "닫기", size: "24px", usage: "시트, 모달, 칩 해제" },
    ],
  },
  {
    library: "vehicle",
    korean: "차량",
    source: "보배드림 차량 아이콘",
    icons: [
      { name: "ic_vehicle_used_car_24", korean: "중고차", size: "24px", usage: "차량 카테고리" },
      { name: "ic_vehicle_truck_24", korean: "트럭 · 특장", size: "24px", usage: "차량 카테고리" },
      { name: "ic_vehicle_bike_24", korean: "바이크", size: "24px", usage: "차량 카테고리" },
      { name: "ic_vehicle_camping_24", korean: "캠핑카", size: "24px", usage: "차량 카테고리" },
      { name: "ic_vehicle_oem_bmw_24", korean: "BMW", size: "24px", usage: "제조사 선택" },
    ],
  },
  {
    library: "commerce",
    korean: "거래",
    source: "보배드림 커스텀 아이콘",
    icons: [
      { name: "ic_commerce_save_24", korean: "찜", size: "24px", usage: "매물 저장" },
      { name: "ic_commerce_call_24", korean: "전화", size: "24px", usage: "딜러 문의" },
      { name: "ic_commerce_chat_24", korean: "채팅", size: "24px", usage: "상담 연결" },
      { name: "ic_commerce_price_down_24", korean: "가격 인하", size: "24px", usage: "가격 변동 배지" },
    ],
  },
  {
    library: "media",
    korean: "미디어",
    source: "보배드림 미디어 아이콘",
    icons: [
      { name: "ic_media_photo_24", korean: "사진", size: "24px", usage: "사진 개수, 갤러리" },
      { name: "ic_media_video_24", korean: "영상", size: "24px", usage: "숏폼, 차량 영상" },
      { name: "ic_media_camera_24", korean: "촬영", size: "24px", usage: "업로드 촬영 도구" },
      { name: "ic_media_play_24", korean: "재생", size: "24px", usage: "동영상 썸네일" },
    ],
  },
];

export const componentSpecs = [
  { name: "BobaBreadcrumb", category: "Navigation", pc: "상단 GNB 아래 전체 경로", mo: "부모 링크 1개와 현재 제목", source: "보배드림 탐색 기준" },
  { name: "BobaButton", category: "Buttons", pc: "40px 높이", mo: "44px 이상 터치 영역", source: "보배드림 버튼 기준" },
  { name: "BobaFilterPanel", category: "Filter", pc: "연식/주행거리/가격/지역/제조사 사이드 필터", mo: "바텀시트 필터와 선택 칩", source: "보배드림 필터 기준" },
  { name: "BobaFilterChip", category: "Filtering", pc: "36px 높이", mo: "34px 높이, horizontal carousel", source: "보배드림 칩 기준" },
  { name: "BobaListingCard", category: "Card/List row", pc: "썸네일 230px, hover shadow", mo: "좌측 썸네일 124px", source: "보배드림 매물 카드 기준" },
  { name: "BobaBadge", category: "Badge", pc: "무사고/진단/급매/실매물 상태", mo: "카드 썸네일과 정보 영역에 20px 이상", source: "보배드림 배지 기준" },
  { name: "BobaGallery", category: "Media", pc: "큰 이미지 + 썸네일 rail", mo: "스와이프 + 카운터", source: "보배드림 갤러리 기준" },
  { name: "BobaSave", category: "Commerce", pc: "outline/active", mo: "44px hit area", source: "보배드림 저장 기준" },
  { name: "BobaRangeDual", category: "Forms", pc: "가격/연식 범위", mo: "바텀시트 내 dual control", source: "보배드림 범위 입력 기준" },
  { name: "BobaPagination", category: "Pagination", pc: "검색 결과 페이지 이동", mo: "더보기 또는 간소 페이지 버튼", source: "보배드림 페이지네이션 기준" },
  { name: "BobaTabs", category: "Tabs", pc: "상세정보/성능점검/보험이력 sticky tab", mo: "상단 고정 anchor tab", source: "보배드림 탭 기준" },
  { name: "BobaNotification", category: "Notification", pc: "견적/문의/오류 toast와 page notice", mo: "snackbar와 inline error", source: "보배드림 알림 기준" },
  { name: "BobaDetailCTA", category: "Sticky action", pc: "우측 문의 패널", mo: "safe-area 하단 고정", source: "eBay Action bar + Sheet" },
];
