// 가상 트럭 30대에 적용하는 형식별 대표 이미지다.
// 실제 제조사·모델 사진이 아니라 UI 동작 검증용 무상표 생성 이미지다.
export const truckScenarioImageV02: Readonly<Record<string, string>> = {
  "truck-001": "truck/pilot/v01/truck_type_cargo_studio_v01.png",
  "truck-002": "truck/pilot/v01/truck_type_cargo_studio_v01.png",
  "truck-003": "truck/pilot/v01/truck_type_cargo_studio_v01.png",
  "truck-004": "truck/pilot/v01/truck_type_cargo_studio_v01.png",
  "truck-005": "truck/pilot/v01/truck_type_wingbody_studio_v01.png",
  "truck-006": "truck/pilot/v01/truck_type_wingbody_studio_v01.png",
  "truck-007": "truck/pilot/v01/truck_type_wingbody_studio_v01.png",
  "truck-008": "truck/pilot/v01/truck_type_wingbody_studio_v01.png",
  "truck-009": "truck/listings/truck_bus_v01.png",
  "truck-010": "truck/listings/truck_bus_v01.png",
  "truck-011": "truck/listings/truck_dump_v01.png",
  "truck-012": "truck/listings/truck_dump_v01.png",
  "truck-013": "truck/pilot/v01/truck_type_crane_studio_v01.png",
  "truck-014": "truck/pilot/v01/truck_type_crane_studio_v01.png",
  "truck-015": "truck/pilot/v01/truck_type_crane_studio_v01.png",
  "truck-016": "truck/listings/truck_tanker_v01.png",
  "truck-017": "truck/listings/truck_tanker_v01.png",
  "truck-018": "truck/listings/truck_camper_v01.png",
  "truck-019": "truck/listings/truck_camper_v01.png",
  "truck-020": "truck/listings/truck_waste_v01.png",
  "truck-021": "truck/listings/truck_waste_v01.png",
  "truck-022": "truck/listings/truck_fish_v01.png",
  "truck-023": "truck/listings/truck_carrier_v01.png",
  "truck-024": "truck/listings/truck_carrier_v01.png",
  "truck-025": "truck/listings/truck_tractor_v01.png",
  "truck-026": "truck/listings/truck_tractor_v01.png",
  "truck-027": "truck/listings/truck_trailer_v01.png",
  "truck-028": "truck/listings/truck_trailer_v01.png",
  "truck-029": "truck/listings/truck_trailer_v01.png",
  "truck-030": "truck/formats/v01/truck_subtype_light_class_v01.png",
};
