// Google Drive `오토홈 바이크 로고` 원본을 흰 배경 제거·알파 trim한 전용 세트.
// 승용 제조사 로고와 경로를 분리해 자동차 카테고리에는 영향을 주지 않는다.
export const bikeBrandLogosV01: Record<string, { file: string; ratio: number; source: "autohome" | "official" }> = {
  "혼다": { file: "BKM001_Honda.png", ratio: 92 / 74, source: "autohome" },
  "야마하": { file: "BKM002_Yamaha.png", ratio: 99 / 22, source: "autohome" },
  "BMW": { file: "BKM003_BMW_Motorrad.png", ratio: 100 / 22, source: "autohome" },
  "스즈키": { file: "BKM004_Suzuki.png", ratio: 100 / 20, source: "autohome" },
  "할리데이비슨": { file: "BKM005_Harley_Davidson.png", ratio: 90 / 70, source: "autohome" },
  "가와사키": { file: "BKM006_Kawasaki.png", ratio: 86 / 43, source: "autohome" },
  "SYM": { file: "BKM007_SYM.png", ratio: 82 / 83, source: "autohome" },
  "베스파": { file: "BKM008_Vespa.png", ratio: 74 / 25, source: "autohome" },
  "로얄엔필드": { file: "BKM009_Royal_Enfield.png", ratio: 560 / 75, source: "official" },
  "두카티": { file: "BKM010_Ducati.png", ratio: 94 / 100, source: "autohome" },
  "AJS": { file: "BKM011_AJS.png", ratio: 560 / 549, source: "official" },
  "CF모토": { file: "BKM012_CFMOTO.png", ratio: 100 / 21, source: "autohome" },
  "KR모터스(효성)": { file: "BKM015_KR_Motors.png", ratio: 88 / 34, source: "autohome" },
  "KR모터스": { file: "BKM015_KR_Motors.png", ratio: 88 / 34, source: "autohome" },
  "KTM": { file: "BKM016_KTM.png", ratio: 100 / 90, source: "autohome" },
  "MV아구스타": { file: "BKM019_MV_Agusta.png", ratio: 100 / 66, source: "autohome" },
  "QJ모터": { file: "BKM020_QJMOTOR.png", ratio: 100 / 9, source: "autohome" },
  "QJ 모터": { file: "BKM020_QJMOTOR.png", ratio: 100 / 9, source: "autohome" },
  "SSR모터스포츠": { file: "BKM021_SSR_Motorsports.png", ratio: 560 / 173, source: "official" },
  "UM모터스": { file: "BKM024_UM_Motorcycles.png", ratio: 560 / 147, source: "official" },
  "고고로": { file: "BKM026_Gogoro.png", ratio: 560 / 156, source: "official" },
  "니우": { file: "BKM027_NIU.png", ratio: 100 / 31, source: "autohome" },
  "대동모빌리티": { file: "BKM028_Daedong_Mobility.png", ratio: 560 / 419, source: "official" },
  "디앤에이모터스(대림)": { file: "BKM029_DNA_Motors.png", ratio: 560 / 199, source: "official" },
  "대림": { file: "BKM029_DNA_Motors.png", ratio: 560 / 199, source: "official" },
  "람브레타": { file: "BKM030_Lambretta.png", ratio: 90 / 14, source: "autohome" },
  "로얄알로이": { file: "BKM031_Royal_Alloy.png", ratio: 61 / 78, source: "autohome" },
  "모토구찌": { file: "BKM035_Moto_Guzzi.png", ratio: 80 / 22, source: "autohome" },
  "몬디알": { file: "BKM037_FB_Mondial.png", ratio: 560 / 354, source: "official" },
  "베넬리": { file: "BKM039_Benelli.png", ratio: 68 / 68, source: "autohome" },
  "벤다": { file: "BKM042_Benda.png", ratio: 76 / 85, source: "autohome" },
  "보그": { file: "BKM043_VOGE.png", ratio: 60 / 67, source: "autohome" },
  "브릭스톤": { file: "BKM046_Brixton.png", ratio: 560 / 363, source: "official" },
  "블루샤크": { file: "BKM047_Blueshark.png", ratio: 560 / 100, source: "official" },
  "빅토리": { file: "BKM049_Victory.png", ratio: 560 / 299, source: "official" },
  "빅토리아": { file: "BKM050_Victoria_Motorrad.png", ratio: 560 / 208, source: "official" },
  "슈퍼쏘코": { file: "BKM051_Super_Soco.png", ratio: 100 / 21, source: "autohome" },
  "스코마디": { file: "BKM052_Scomadi.png", ratio: 445 / 560, source: "official" },
  "아프릴리아": { file: "BKM055_Aprilia.png", ratio: 100 / 36, source: "autohome" },
  "에릭": { file: "BKM056_EBR_Erik_Buell.png", ratio: 560 / 421, source: "official" },
  "우랄": { file: "BKM059_Ural.png", ratio: 68 / 68, source: "autohome" },
  "이탈젯": { file: "BKM063_Italjet.png", ratio: 68 / 23, source: "autohome" },
  "인디언모터사이클": { file: "BKM064_Indian_Motorcycle.png", ratio: 100 / 36, source: "autohome" },
  "존테스": { file: "BKM067_Zontes.png", ratio: 96 / 40, source: "autohome" },
  "질레라": { file: "BKM068_Gilera.png", ratio: 381 / 560, source: "official" },
  "카요": { file: "BKM070_Kayo.png", ratio: 560 / 222, source: "official" },
  "캔암": { file: "BKM071_Can_Am.png", ratio: 68 / 68, source: "autohome" },
  "쿠팝": { file: "BKM073_Coopop.png", ratio: 560 / 96, source: "official" },
  "키웨이": { file: "BKM074_Keeway.png", ratio: 560 / 102, source: "official" },
  "킴코": { file: "BKM076_KYMCO.png", ratio: 86 / 62, source: "autohome" },
  "트라이엄프": { file: "BKM078_Triumph.png", ratio: 100 / 21, source: "autohome" },
  "폴라리스": { file: "BKM079_Polaris.png", ratio: 100 / 11, source: "autohome" },
  "푸조": { file: "BKM080_Peugeot_Motocycles.png", ratio: 77 / 84, source: "autohome" },
  "피아지오": { file: "BKM082_Piaggio.png", ratio: 98 / 34, source: "autohome" },
  "하우주": { file: "BKM083_Haojue.png", ratio: 68 / 68, source: "autohome" },
  "한솜모터스": { file: "BKM084_Hansom_Motors.png", ratio: 560 / 68, source: "official" },
  "허스크바나": { file: "BKM085_Husqvarna.png", ratio: 55 / 68, source: "autohome" },
  "기타 제조사": { file: "BKM086_Others.png", ratio: 1, source: "official" },
  "기타": { file: "BKM086_Others.png", ratio: 1, source: "official" },
};
