export type BikeScenarioV04Row = {
  scenario_id: string;
  image_file: string;
  title: string;
  brand: string;
  model: string;
  year: number;
  mileage_km: number;
  displacement_cc: number;
  genre: string;
  license_class: string;
  fuel: string;
  transmission: string;
  region: string;
  price_krw: number;
  seller_type: string;
  condition: string;
  certified: string;
  delivery: string;
  quickfilter_tags: readonly string[];
  is_virtual: boolean;
  source_manifest_version: string;
  scenario_version: string;
  seller_name: string;
  seller_address: string;
  seller_contact: string;
  seller_intro: string;
  business_hours: string;
};

export const bikeScenarioV04 = [
  {
    "scenario_id": "bike-001",
    "image_file": "bike_listing_001_v01.webp",
    "title": "혼다 레블 500",
    "brand": "혼다",
    "model": "레블 500",
    "year": 2023,
    "mileage_km": 9680,
    "displacement_cc": 471,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 6500000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "크루저",
      "471cc",
      "서울",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "라이드온 모터스 서울 01점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-002",
    "image_file": "bike_listing_002_v01.webp",
    "title": "스즈키 하야부사",
    "brand": "스즈키",
    "model": "하야부사",
    "year": 2022,
    "mileage_km": 13300,
    "displacement_cc": 1340,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남",
    "price_krw": 16500000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "1340cc",
      "경남",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "모토브릿지 경남 02점 (가상)",
    "seller_address": "경상남도 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-003",
    "image_file": "bike_listing_003_v01.webp",
    "title": "존테스 125 G1",
    "brand": "존테스",
    "model": "125 G1",
    "year": 2023,
    "mileage_km": 14200,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전북",
    "price_krw": 2000000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "존테스",
      "네이키드",
      "124cc",
      "전북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더003 (가상)",
    "seller_address": "전북특별자치도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-004",
    "image_file": "bike_listing_004_v01.webp",
    "title": "두카티 파니갈레 V2",
    "brand": "두카티",
    "model": "파니갈레 V2",
    "year": 2023,
    "mileage_km": 6000,
    "displacement_cc": 955,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "울산",
    "price_krw": 25000000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "두카티",
      "스포츠",
      "955cc",
      "울산",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "바이크허브 울산 04점 (가상)",
    "seller_address": "울산광역시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-005",
    "image_file": "bike_listing_005_v01.webp",
    "title": "스즈키 버그만 스트리트 125 EX",
    "brand": "스즈키",
    "model": "버그만 스트리트 125 EX",
    "year": 2024,
    "mileage_km": 23644,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 1690000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "스즈키",
      "스쿠터",
      "125cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "로드메이트 서울 05점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-006",
    "image_file": "bike_listing_006_v01.webp",
    "title": "야마하 NMAX 125",
    "brand": "야마하",
    "model": "NMAX 125",
    "year": 2025,
    "mileage_km": 12738,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 용산",
    "price_krw": 3400000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "125cc",
      "서울 용산",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더006 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-007",
    "image_file": "bike_listing_007_v01.webp",
    "title": "베스파 LX 125",
    "brand": "베스파",
    "model": "LX 125",
    "year": 2022,
    "mileage_km": 1500,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 2500000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "베스파",
      "스쿠터",
      "124cc",
      "서울",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "모토브릿지 서울 07점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-008",
    "image_file": "bike_listing_008_v01.webp",
    "title": "혼다 CBR 650 R MT",
    "brand": "혼다",
    "model": "CBR 650 R MT",
    "year": 2023,
    "mileage_km": 32000,
    "displacement_cc": 649,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "대전",
    "price_krw": 7500000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "649cc",
      "대전",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "투휠마켓 대전 08점 (가상)",
    "seller_address": "대전광역시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-009",
    "image_file": "bike_listing_009_v01.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2020,
    "mileage_km": 41500,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경북",
    "price_krw": 1300000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더009 (가상)",
    "seller_address": "경상북도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-010",
    "image_file": "bike_listing_010_v01.webp",
    "title": "야마하 MT 09 트레이서",
    "brand": "야마하",
    "model": "MT 09 트레이서",
    "year": 2015,
    "mileage_km": 37245,
    "displacement_cc": 847,
    "genre": "투어러",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 6000000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "투어러",
      "847cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "로드메이트 경기 10점 (가상)",
    "seller_address": "경기도 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-011",
    "image_file": "bike_listing_011_v01.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2025,
    "mileage_km": 36014,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 용산",
    "price_krw": 4780000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "서울 용산",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "라이드온 모터스 서울 용산 11점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-012",
    "image_file": "bike_listing_012_v01.webp",
    "title": "야마하 NMAX 155",
    "brand": "야마하",
    "model": "NMAX 155",
    "year": 2026,
    "mileage_km": 2600,
    "displacement_cc": 155,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "대전",
    "price_krw": 5200000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "155cc",
      "대전",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더012 (가상)",
    "seller_address": "대전광역시 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-013",
    "image_file": "bike_listing_013_v01.webp",
    "title": "야마하 NMAX 125",
    "brand": "야마하",
    "model": "NMAX 125",
    "year": 2023,
    "mileage_km": 9400,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기",
    "price_krw": 2800000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "125cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "투휠마켓 경기 13점 (가상)",
    "seller_address": "경기도 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-014",
    "image_file": "bike_listing_014_v01.webp",
    "title": "할리데이비슨 스트리트 밥",
    "brand": "할리데이비슨",
    "model": "스트리트 밥",
    "year": 2025,
    "mileage_km": 4500,
    "displacement_cc": 1868,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천",
    "price_krw": 24000000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "할리데이비슨",
      "크루저",
      "1868cc",
      "인천",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "바이크허브 인천 14점 (가상)",
    "seller_address": "인천광역시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-015",
    "image_file": "bike_listing_015_v01.webp",
    "title": "가와사키 버시스 X 250",
    "brand": "가와사키",
    "model": "버시스 X 250",
    "year": 2017,
    "mileage_km": 30500,
    "displacement_cc": 248,
    "genre": "투어러",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전북",
    "price_krw": 3100000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "가와사키",
      "투어러",
      "248cc",
      "전북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더015 (가상)",
    "seller_address": "전북특별자치도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-016",
    "image_file": "bike_listing_016_v01.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2025,
    "mileage_km": 3006,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 용산",
    "price_krw": 6900000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "서울 용산",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "라이드온 모터스 서울 용산 16점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-017",
    "image_file": "bike_listing_017_v01.webp",
    "title": "혼다 XZ 100",
    "brand": "혼다",
    "model": "XZ 100",
    "year": 2006,
    "mileage_km": 13000,
    "displacement_cc": 99,
    "genre": "언더본",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "부산",
    "price_krw": 1500000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "언더본",
      "99cc",
      "부산",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "모토브릿지 부산 17점 (가상)",
    "seller_address": "부산광역시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-018",
    "image_file": "bike_listing_018_v01.webp",
    "title": "KTM 125 듀크",
    "brand": "KTM",
    "model": "125 듀크",
    "year": 2023,
    "mileage_km": 2500,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전남",
    "price_krw": 3300000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "KTM",
      "네이키드",
      "124cc",
      "전남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더018 (가상)",
    "seller_address": "전라남도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-019",
    "image_file": "bike_listing_019_v01.webp",
    "title": "혼다 CBR 650 R E-CLUTCH",
    "brand": "혼다",
    "model": "CBR 650 R E-CLUTCH",
    "year": 2025,
    "mileage_km": 8800,
    "displacement_cc": 649,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 10800000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "649cc",
      "서울",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "바이크허브 서울 19점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-020",
    "image_file": "bike_listing_020_v01.webp",
    "title": "혼다 MSX 125 그롬",
    "brand": "혼다",
    "model": "MSX 125 그롬",
    "year": 2025,
    "mileage_km": 204,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "용산점",
    "price_krw": 3600000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "네이키드",
      "124cc",
      "용산점",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "로드메이트 용산 20점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-021",
    "image_file": "bike_listing_021_v01.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2018,
    "mileage_km": 36314,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남",
    "price_krw": 2800000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더021 (가상)",
    "seller_address": "경상남도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-022",
    "image_file": "bike_listing_022_v01.webp",
    "title": "가와사키 닌자 400 ABS",
    "brand": "가와사키",
    "model": "닌자 400 ABS",
    "year": 2019,
    "mileage_km": 25987,
    "displacement_cc": 399,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "대구",
    "price_krw": 5000000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "가와사키",
      "스포츠",
      "399cc",
      "대구",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "모토브릿지 대구 22점 (가상)",
    "seller_address": "대구광역시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-023",
    "image_file": "bike_listing_023_v01.webp",
    "title": "베스파 스프린트 125 저스틴비버",
    "brand": "베스파",
    "model": "스프린트 125 저스틴비버",
    "year": 2022,
    "mileage_km": 7999,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 5000000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "베스파",
      "스쿠터",
      "124cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "투휠마켓 서울 23점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-024",
    "image_file": "bike_listing_024_v01.webp",
    "title": "혼다 C 125",
    "brand": "혼다",
    "model": "C 125",
    "year": 2025,
    "mileage_km": 21116,
    "displacement_cc": 124,
    "genre": "언더본",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 2800000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "언더본",
      "124cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더024 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-025",
    "image_file": "bike_listing_025_v01.webp",
    "title": "가와사키 닌자 1000 SX",
    "brand": "가와사키",
    "model": "닌자 1000 SX",
    "year": 2020,
    "mileage_km": 27129,
    "displacement_cc": 1043,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 10550000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "가와사키",
      "스포츠",
      "1043cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "로드메이트 경기 25점 (가상)",
    "seller_address": "경기도 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-026",
    "image_file": "bike_listing_026_v01.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2023,
    "mileage_km": 58000,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기",
    "price_krw": 4200000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "경기",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "라이드온 모터스 경기 26점 (가상)",
    "seller_address": "경기도 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-027",
    "image_file": "bike_listing_027_v01.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2019,
    "mileage_km": 33800,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남",
    "price_krw": 4450000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더027 (가상)",
    "seller_address": "경상남도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-028",
    "image_file": "bike_listing_028_v01.webp",
    "title": "KR모터스 아퀼라 125",
    "brand": "KR모터스",
    "model": "아퀼라 125",
    "year": 2020,
    "mileage_km": 2048,
    "displacement_cc": 124,
    "genre": "크루저",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 2250000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "KR모터스",
      "크루저",
      "124cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "투휠마켓 경기 28점 (가상)",
    "seller_address": "경기도 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-029",
    "image_file": "bike_listing_029_v01.webp",
    "title": "혼다 MSX 125 SF",
    "brand": "혼다",
    "model": "MSX 125 SF",
    "year": 2017,
    "mileage_km": 21500,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 1700000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "네이키드",
      "124cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "바이크허브 서울 29점 (가상)",
    "seller_address": "서울특별시 가상시 테스트구 바이크 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "bike-030",
    "image_file": "bike_listing_030_v01.webp",
    "title": "스즈키 하야부사",
    "brand": "스즈키",
    "model": "하야부사",
    "year": 2022,
    "mileage_km": 24000,
    "displacement_cc": 1340,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 18500000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "1340cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 라이더030 (가상)",
    "seller_address": "경기도 가상시 테스트구 바이크 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "바이크 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  }
] as const satisfies readonly BikeScenarioV04Row[];
