import type { BikeScenarioV07Row } from "./scenario-v07";

/** 바이크 매물 v08(2026-10-08): 사용자 구글 시트 「가상 매물 시나리오 › 바이크」 50행(라이트바겐 매물 수집본)을 옮긴 값.
 *  제조사·모델·연식·주행·지역·가격·배기량·서류·상태·튜닝·정비 요약은 시트 그대로, 판매자 이름·연락처는 가상 값(실제 판매자명 미사용),
 *  장르·면허·변속기는 모델 기준으로 정한 값. 원본 상세 URL·매물 ID는 저장하지 않는다. 사진은 public/assets/bike/listings/v08/. */
export type BikeScenarioV08Row = BikeScenarioV07Row & {
  documents: string;
  condition_summary: string;
  tuning_summary: string;
  maintenance_summary: string;
  posted_days: number;
  sheet_row: number;
};

export const bikeScenarioV08: BikeScenarioV08Row[] = [
  {
    "scenario_id": "bike-v08-01",
    "image_file": "v08/bike-v08-01.webp",
    "title": "가와사키 닌자 650 ABS",
    "brand": "가와사키",
    "model": "닌자 650 ABS",
    "year": 2018,
    "mileage_km": 52000,
    "displacement_cc": 649,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기 포천시",
    "price_krw": 4000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "가와사키",
      "스포츠",
      "649cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경기 포천시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "서류 없음",
    "condition_summary": "상태 괜찮음; 제꿍·슬립 흔적 있음; 사고 이력 없음",
    "tuning_summary": "블랙박스, 휴대폰 거치대, USB충전포트, 포크·프레임 슬라이더",
    "maintenance_summary": "대소기어·체인 49,500km; 앞 패드 50,000km; 엔진오일·필터 50,500km",
    "posted_days": 0,
    "sheet_row": 1
  },
  {
    "scenario_id": "bike-v08-02",
    "image_file": "v08/bike-v08-02.webp",
    "title": "스즈키 GSX R 1000 R",
    "brand": "스즈키",
    "model": "GSX R 1000 R",
    "year": 2019,
    "mileage_km": 35075,
    "displacement_cc": 999,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 남동구",
    "price_krw": 12290000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "999cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 남동구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "퀵시프트, 휴대폰 거치대, 요시무라 머플러, 아라시 백스텝",
    "maintenance_summary": "엔진오일·필터, 브레이크 패드, 에어필터",
    "posted_days": 0,
    "sheet_row": 2
  },
  {
    "scenario_id": "bike-v08-03",
    "image_file": "v08/bike-v08-03.webp",
    "title": "스즈키 GSX R 1000 R",
    "brand": "스즈키",
    "model": "GSX R 1000 R",
    "year": 2017,
    "mileage_km": 17828,
    "displacement_cc": 999,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 성북구",
    "price_krw": 16500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "999cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 성북구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "램마운트, USB포트, 지넷 2채널 블랙박스, 슬라이더류, 요시무라 R11sq 풀시스템",
    "maintenance_summary": "포크 오버홀, 배터리 최근 교체",
    "posted_days": 9,
    "sheet_row": 3
  },
  {
    "scenario_id": "bike-v08-04",
    "image_file": "v08/bike-v08-04.webp",
    "title": "혼다 줌머",
    "brand": "혼다",
    "model": "줌머",
    "year": 2007,
    "mileage_km": 1,
    "displacement_cc": 49,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 구로구",
    "price_krw": 3000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스쿠터",
      "49cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 구로구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 여부 미표기",
    "tuning_summary": "핫랩 풀시스템 머플러(구변완료), 디스크브레이크 개조, 광폭휠, 탑박스, LED헤드라이트",
    "maintenance_summary": "앞뒤 피렐리 타이어·엔진오일·냉각수 교체, 배터리 전압체크, 전체점검",
    "posted_days": 153,
    "sheet_row": 4
  },
  {
    "scenario_id": "bike-v08-05",
    "image_file": "v08/bike-v08-05.webp",
    "title": "혼다 슈퍼 커브 110",
    "brand": "혼다",
    "model": "슈퍼 커브 110",
    "year": 2021,
    "mileage_km": 2050,
    "displacement_cc": 109,
    "genre": "언더본",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 미추홀구",
    "price_krw": 2600000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "언더본",
      "109cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 미추홀구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "충전식 거치대, 짐대, USB포트, 윈드스크린, 핸들열선, 캐리어, 바구니, 텐덤시트",
    "maintenance_summary": "엔진오일·필터; 앞뒤 타이어 90% 이상, 패드·대소기어 80% 이상(판매자 기재)",
    "posted_days": 0,
    "sheet_row": 5
  },
  {
    "scenario_id": "bike-v08-06",
    "image_file": "v08/bike-v08-06.webp",
    "title": "가와사키 Z 900",
    "brand": "가와사키",
    "model": "Z 900",
    "year": 2023,
    "mileage_km": 11500,
    "displacement_cc": 948,
    "genre": "네이키드",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 강동구",
    "price_krw": 10500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "가와사키",
      "네이키드",
      "948cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 강동구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "블랙박스, 거치대, USB포트, 윈드스크린, 슬라이더, 라디에이터 그릴; 짭크라 장착(구변 안함)",
    "maintenance_summary": "8,100km 센터 전체점검·오일·필터 교환; 10,000km 엔진오일 교환",
    "posted_days": 0,
    "sheet_row": 6
  },
  {
    "scenario_id": "bike-v08-07",
    "image_file": "v08/bike-v08-07.webp",
    "title": "모토구찌 AUDACE",
    "brand": "모토구찌",
    "model": "AUDACE",
    "year": 2016,
    "mileage_km": 20000,
    "displacement_cc": 1380,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기 안양시 만안구",
    "price_krw": 13000000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "모토구찌",
      "크루저",
      "1380cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경기 안양시 만안구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, USB포트; 카본 버전, 수전 도색, 아고니스 배기 구조변경",
    "maintenance_summary": "16,000km대 소모품 전체 교체; 뒷타이어 교체 필요",
    "posted_days": 23,
    "sheet_row": 7
  },
  {
    "scenario_id": "bike-v08-08",
    "image_file": "v08/bike-v08-08.webp",
    "title": "야마하 NMAX 125",
    "brand": "야마하",
    "model": "NMAX 125",
    "year": 2025,
    "mileage_km": 14188,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 용산구",
    "price_krw": 3200000,
    "seller_type": "인증 판매업체",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "125cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "모토브릿지 용산점 (가상)",
    "seller_address": "서울 용산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "결제 이후 필수 서류 제공",
    "condition_summary": "생활 흠집 및 사용감 존재; 상세 진단 기재",
    "tuning_summary": "자석 충전 거치대, 시트 방석, 스탠드 클립, 알루미늄 탑박스·리다이, 소형 버거 가방",
    "maintenance_summary": "배터리 교체 필요; 냉각수·엔진오일·브레이크액 양호; 앞 타이어 60~70%, 뒤 40~50%",
    "posted_days": 1,
    "sheet_row": 8
  },
  {
    "scenario_id": "bike-v08-09",
    "image_file": "v08/bike-v08-09.webp",
    "title": "빅토리아 니키 125",
    "brand": "빅토리아",
    "model": "니키 125",
    "year": 2022,
    "mileage_km": 14420,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "인천 부평구",
    "price_krw": 1200000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "빅토리아",
      "스쿠터",
      "124cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 부평구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 무선충전 거치대",
    "maintenance_summary": "10,000km 구동계점검; 14,000km 오일교환; 12,000km 뒷타이어 교체",
    "posted_days": 7,
    "sheet_row": 9
  },
  {
    "scenario_id": "bike-v08-10",
    "image_file": "v08/bike-v08-10.webp",
    "title": "야마하 NMAX 125",
    "brand": "야마하",
    "model": "NMAX 125",
    "year": 2022,
    "mileage_km": 122000,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "광주 광산구",
    "price_krw": 1100000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "125cc",
      "광주",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "광주 광산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립 흔적 있음; 사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, 탑박스, 짐대, 윈드스크린, 핸들열선, 배달 튜닝",
    "maintenance_summary": "엔진오일 교체",
    "posted_days": 1,
    "sheet_row": 10
  },
  {
    "scenario_id": "bike-v08-11",
    "image_file": "v08/bike-v08-11.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2023,
    "mileage_km": 5775,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경북 상주시",
    "price_krw": 6000000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경북",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경북 상주시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, 블랙박스, USB포트, 엔진가드, 포크 슬라이더",
    "maintenance_summary": "엔진오일·필터, 에어필터",
    "posted_days": 0,
    "sheet_row": 11
  },
  {
    "scenario_id": "bike-v08-12",
    "image_file": "v08/bike-v08-12.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2019,
    "mileage_km": 58000,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "광주 광산구",
    "price_krw": 1700000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "광주",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "광주 광산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "탑박스, 짐대, 핸들열선",
    "maintenance_summary": "엔진오일·필터; 상세설명에 헤드 수리 및 로커암 흡기·배기 교체 기재",
    "posted_days": 1,
    "sheet_row": 12
  },
  {
    "scenario_id": "bike-v08-13",
    "image_file": "v08/bike-v08-13.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2024,
    "mileage_km": 15000,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기 의정부시",
    "price_krw": 5000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경기 의정부시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "인산철 배터리, 전후 블랙박스, 전자크락션, 윈드스크린, 탑박스, 핸들열선, 거치대, 핸들가드",
    "maintenance_summary": "엔진오일·필터, 패드, 에어필터, 배터리, 타이어",
    "posted_days": 23,
    "sheet_row": 13
  },
  {
    "scenario_id": "bike-v08-14",
    "image_file": "v08/bike-v08-14.webp",
    "title": "존테스 368 G",
    "brand": "존테스",
    "model": "368 G",
    "year": 2026,
    "mileage_km": 9981,
    "displacement_cc": 367,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 용산구",
    "price_krw": 5820000,
    "seller_type": "인증 판매업체",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "존테스",
      "스쿠터",
      "367cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "모토브릿지 용산점 (가상)",
    "seller_address": "서울 용산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "결제 이후 필수 서류 제공",
    "condition_summary": "생활 흠집 및 사용감 존재; 상세 진단 기재",
    "tuning_summary": "알루미늄 탑박스·리다이, 소쿠리 자석 거치대",
    "maintenance_summary": "엔진오일·필터 교체 권장; 뒤 타이어 0%, 앞 40%; 패드 앞 40%, 뒤 10~20%",
    "posted_days": 1,
    "sheet_row": 14
  },
  {
    "scenario_id": "bike-v08-15",
    "image_file": "v08/bike-v08-15.webp",
    "title": "혼다 PCX 125",
    "brand": "혼다",
    "model": "PCX 125",
    "year": 2021,
    "mileage_km": 20012,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "강원 원주시",
    "price_krw": 2100000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스쿠터",
      "124cc",
      "강원",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "강원 원주시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립 흔적 있음; 사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, 탑박스",
    "maintenance_summary": "미표기",
    "posted_days": 3,
    "sheet_row": 15
  },
  {
    "scenario_id": "bike-v08-16",
    "image_file": "v08/bike-v08-16.webp",
    "title": "가와사키 Z 400",
    "brand": "가와사키",
    "model": "Z 400",
    "year": 2019,
    "mileage_km": 6900,
    "displacement_cc": 398,
    "genre": "네이키드",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전남 광양시",
    "price_krw": 5000000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "가와사키",
      "네이키드",
      "398cc",
      "전남",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "전남 광양시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "신차급; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "USB포트, 엔진가드, 포크·프레임 슬라이더; 6월 검사 완료 기재",
    "maintenance_summary": "엔진오일·필터, 타이어, 배터리, 브레이크 오일; 6,000km 부근 교체",
    "posted_days": 0,
    "sheet_row": 16
  },
  {
    "scenario_id": "bike-v08-17",
    "image_file": "v08/bike-v08-17.webp",
    "title": "허스크바나 스바르트필렌 125",
    "brand": "허스크바나",
    "model": "스바르트필렌 125",
    "year": 2022,
    "mileage_km": 9400,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "강원 강릉시",
    "price_krw": 2600000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "허스크바나",
      "네이키드",
      "124cc",
      "강원",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "강원 강릉시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "USB포트, 허스크바나 탱크백, SP커넥터 거치대, 사이드백 브라켓",
    "maintenance_summary": "9,000km 엔진오일·필터·에어필터; 9,300km 체인세척·루브",
    "posted_days": 0,
    "sheet_row": 17
  },
  {
    "scenario_id": "bike-v08-18",
    "image_file": "v08/bike-v08-18.webp",
    "title": "혼다 레블 500",
    "brand": "혼다",
    "model": "레블 500",
    "year": 2024,
    "mileage_km": 5000,
    "displacement_cc": 471,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 서해구",
    "price_krw": 7000000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "크루저",
      "471cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 서해구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 거치대",
    "maintenance_summary": "엔진오일·필터",
    "posted_days": 24,
    "sheet_row": 18
  },
  {
    "scenario_id": "bike-v08-19",
    "image_file": "v08/bike-v08-19.webp",
    "title": "BMW S 1000 RR",
    "brand": "BMW",
    "model": "S 1000 RR",
    "year": 2022,
    "mileage_km": 20000,
    "displacement_cc": 999,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "울산 동구",
    "price_krw": 21000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "BMW",
      "스포츠",
      "999cc",
      "울산",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "울산 동구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립 흔적 있음; 사고 이력 없음",
    "tuning_summary": "블랙박스, 거치대, 핸들열선, USB포트, 윈드스크린, 프레임 슬라이더, 정품 M팩 카울",
    "maintenance_summary": "엔진오일·필터, 패드, 브레이크 오일",
    "posted_days": 0,
    "sheet_row": 19
  },
  {
    "scenario_id": "bike-v08-20",
    "image_file": "v08/bike-v08-20.webp",
    "title": "가와사키 닌자 ZX 10 R",
    "brand": "가와사키",
    "model": "닌자 ZX 10 R",
    "year": 2021,
    "mileage_km": 14206,
    "displacement_cc": 998,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 용산구",
    "price_krw": 18500000,
    "seller_type": "인증 판매업체",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "가와사키",
      "스포츠",
      "998cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "모토브릿지 용산점 (가상)",
    "seller_address": "서울 용산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "결제 이후 필수 서류 제공",
    "condition_summary": "생활 흠집 및 사용감 존재; 상세 진단 기재",
    "tuning_summary": "USB포트, 윙렛, 떼르미뇨니 슬립온(구변X), 쿼드락, 탱크·니그립패드, 휀다리스킷, 스모크 스크린",
    "maintenance_summary": "엔진오일·필터·냉각수·뒤 브레이크액 교체 권장; 앞 타이어 98%, 뒤 50%; 패드 앞 30%, 뒤 50%",
    "posted_days": 1,
    "sheet_row": 20
  },
  {
    "scenario_id": "bike-v08-21",
    "image_file": "v08/bike-v08-21.webp",
    "title": "허스크바나 비트필렌 401",
    "brand": "허스크바나",
    "model": "비트필렌 401",
    "year": 2023,
    "mileage_km": 2893,
    "displacement_cc": 373,
    "genre": "네이키드",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 남동구",
    "price_krw": 3890000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "허스크바나",
      "네이키드",
      "373cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 남동구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "사이드미러, 2채널 블랙박스",
    "maintenance_summary": "엔진오일",
    "posted_days": 26,
    "sheet_row": 21
  },
  {
    "scenario_id": "bike-v08-22",
    "image_file": "v08/bike-v08-22.webp",
    "title": "혼다 CBR 600 RR",
    "brand": "혼다",
    "model": "CBR 600 RR",
    "year": 2025,
    "mileage_km": 12400,
    "displacement_cc": 600,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "부산 사하구",
    "price_krw": 15000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "600cc",
      "부산",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "부산 사하구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "서류 없음",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "블랙박스, USB포트, 윈드스크린, 엔진가드, 포크·프레임 슬라이더",
    "maintenance_summary": "11,800km 리콜 수리; 1,000km마다 오일교환, 오일교환 2회당 필터 1회 교환",
    "posted_days": 80,
    "sheet_row": 22
  },
  {
    "scenario_id": "bike-v08-23",
    "image_file": "v08/bike-v08-23.webp",
    "title": "혼다 PCX 125",
    "brand": "혼다",
    "model": "PCX 125",
    "year": 2022,
    "mileage_km": 38800,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 노원구",
    "price_krw": 2400000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스쿠터",
      "124cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 노원구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "자석·알존 거치대, 이소타 롱스크린, YSS 쇼바, XRT 레버, 핸들열선, 스탠드 시동센서, 알루미늄박스",
    "maintenance_summary": "37,000km 구동계 전체교환; 패드·디스크 교환; 앞뒤 타이어 70% 이상",
    "posted_days": 0,
    "sheet_row": 23
  },
  {
    "scenario_id": "bike-v08-24",
    "image_file": "v08/bike-v08-24.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2016,
    "mileage_km": 57000,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "부산 사상구",
    "price_krw": 2500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "부산",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "부산 사상구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "떼르미뇨니 풀배기(구변완료), 방탄 데칼, RCB 백스텝, 조절식 핸들, GB레이싱 엔진가드, 거치대 등",
    "maintenance_summary": "현 차주 인수 후 정비 없음 기재",
    "posted_days": 0,
    "sheet_row": 24
  },
  {
    "scenario_id": "bike-v08-25",
    "image_file": "v08/bike-v08-25.webp",
    "title": "BMW C 400 GT",
    "brand": "BMW",
    "model": "C 400 GT",
    "year": 2023,
    "mileage_km": 4204,
    "displacement_cc": 350,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "인천 남동구",
    "price_krw": 7500000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "BMW",
      "스쿠터",
      "350cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 남동구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "블랙박스, 탑박스, 짐대, USB포트, 핸들열선",
    "maintenance_summary": "엔진오일",
    "posted_days": 26,
    "sheet_row": 25
  },
  {
    "scenario_id": "bike-v08-26",
    "image_file": "v08/bike-v08-26.webp",
    "title": "혼다 벤리 110",
    "brand": "혼다",
    "model": "벤리 110",
    "year": 2015,
    "mileage_km": 11442,
    "displacement_cc": 108,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 성북구",
    "price_krw": 1650000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스쿠터",
      "108cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 성북구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 1,
    "sheet_row": 26
  },
  {
    "scenario_id": "bike-v08-27",
    "image_file": "v08/bike-v08-27.webp",
    "title": "할리데이비슨 883 슈퍼로우",
    "brand": "할리데이비슨",
    "model": "883 슈퍼로우",
    "year": 2017,
    "mileage_km": 21400,
    "displacement_cc": 883,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "강원 원주시",
    "price_krw": 7500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "할리데이비슨",
      "크루저",
      "883cc",
      "강원",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "강원 원주시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "좌우 새들백, 탱크백, 정품 LED헤드라이트, 포워드스텝, 발판, 엔진가드, 짐받이 등",
    "maintenance_summary": "20,000km 3종 오일 교체; 엔진오일·필터",
    "posted_days": 10,
    "sheet_row": 27
  },
  {
    "scenario_id": "bike-v08-28",
    "image_file": "v08/bike-v08-28.webp",
    "title": "혼다 포르자 350",
    "brand": "혼다",
    "model": "포르자 350",
    "year": 2024,
    "mileage_km": 23992,
    "displacement_cc": 330,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울 용산구",
    "price_krw": 4910000,
    "seller_type": "인증 판매업체",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "스쿠터",
      "330cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "모토브릿지 용산점 (가상)",
    "seller_address": "서울 용산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "결제 이후 필수 서류 제공",
    "condition_summary": "생활 흠집 및 사용감 존재; 상세 진단 기재",
    "tuning_summary": "알루미늄 탑박스·캐리어, 멀티바, 자석 충전 거치대, 컵홀더, 확장 스크린, 열선그립",
    "maintenance_summary": "냉각수 플러싱·보충 완료; 엔진오일·브레이크액 양호; 패드 앞 약20%, 뒤 약30%",
    "posted_days": 1,
    "sheet_row": 28
  },
  {
    "scenario_id": "bike-v08-29",
    "image_file": "v08/bike-v08-29.webp",
    "title": "할리데이비슨 다이나 스트리트밥",
    "brand": "할리데이비슨",
    "model": "다이나 스트리트밥",
    "year": 2013,
    "mileage_km": 39100,
    "displacement_cc": 1584,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기 고양시 덕양구",
    "price_krw": 11000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "할리데이비슨",
      "크루저",
      "1584cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경기 고양시 덕양구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "서류 없음",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "Screamin' Eagle 머플러(구변완료), S&S 오픈 흡기, Fat Bob 핸들, 로우라이더 쇼바, 뒤 튜브리스, 무선충전 거치대",
    "maintenance_summary": "2026-08 환경검사; 2026-03 엔진·미션·프라이머리 오일교환; 2024 배터리 교체",
    "posted_days": 0,
    "sheet_row": 29
  },
  {
    "scenario_id": "bike-v08-30",
    "image_file": "v08/bike-v08-30.webp",
    "title": "스즈키 하야부사",
    "brand": "스즈키",
    "model": "하야부사",
    "year": 2022,
    "mileage_km": 31600,
    "displacement_cc": 1340,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남 김해시",
    "price_krw": 14000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "1340cc",
      "경남",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경남 김해시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "앞뒤·엔진 슬라이더, 디젤 충전기, SP커넥트, 이노브 2채널 블랙박스, 캐노피; 순정 머플러",
    "maintenance_summary": "22,000km대 소모품 교환 기재; 이후 모튤7100 오일 정기교환, 에어필터·패드·냉각수·오일류 교체",
    "posted_days": 0,
    "sheet_row": 30
  },
  {
    "scenario_id": "bike-v08-31",
    "image_file": "v08/bike-v08-31.webp",
    "title": "로얄엔필드 히말라얀",
    "brand": "로얄엔필드",
    "model": "히말라얀",
    "year": 2023,
    "mileage_km": 10227,
    "displacement_cc": 411,
    "genre": "멀티퍼포즈",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 영등포구",
    "price_krw": 2000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "로얄엔필드",
      "멀티퍼포즈",
      "411cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 영등포구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍·슬립 흔적 있음; 사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, 탑박스, 머플러 유리섬유",
    "maintenance_summary": "1개월 전 배터리·엔진오일 교체; 타이어 항목 기재",
    "posted_days": 0,
    "sheet_row": 31
  },
  {
    "scenario_id": "bike-v08-32",
    "image_file": "v08/bike-v08-32.webp",
    "title": "가와사키 발칸 650 ABS",
    "brand": "가와사키",
    "model": "발칸 650 ABS",
    "year": 2023,
    "mileage_km": 400,
    "displacement_cc": 649,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 서해구",
    "price_krw": 8800000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "가와사키",
      "크루저",
      "649cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 서해구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, 블랙박스, 탑박스",
    "maintenance_summary": "엔진오일",
    "posted_days": 8,
    "sheet_row": 32
  },
  {
    "scenario_id": "bike-v08-33",
    "image_file": "v08/bike-v08-33.webp",
    "title": "혼다 CBR 650 R MT",
    "brand": "혼다",
    "model": "CBR 650 R MT",
    "year": 2023,
    "mileage_km": 11000,
    "displacement_cc": 649,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 서해구",
    "price_krw": 8500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "649cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 서해구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 슬립 흔적 있음; 제꿍·사고 이력 없음",
    "tuning_summary": "블랙박스",
    "maintenance_summary": "엔진오일",
    "posted_days": 1,
    "sheet_row": 33
  },
  {
    "scenario_id": "bike-v08-34",
    "image_file": "v08/bike-v08-34.webp",
    "title": "트라이엄프 스크램블러 1200 XE",
    "brand": "트라이엄프",
    "model": "스크램블러 1200 XE",
    "year": 2024,
    "mileage_km": 7500,
    "displacement_cc": 1200,
    "genre": "클래식",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천 계양구",
    "price_krw": 17500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "트라이엄프",
      "클래식",
      "1200cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 계양구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "블랙박스, USB포트, 열선그립, 엔진가드, 사이드백·마운트, 포크프로텍터, 라디에이터가드, 너클가드 등",
    "maintenance_summary": "미표기",
    "posted_days": 0,
    "sheet_row": 34
  },
  {
    "scenario_id": "bike-v08-35",
    "image_file": "v08/bike-v08-35.webp",
    "title": "한솜모터스 베네트 125",
    "brand": "한솜모터스",
    "model": "베네트 125",
    "year": 2023,
    "mileage_km": 3800,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "인천 서해구",
    "price_krw": 2250000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "한솜모터스",
      "스쿠터",
      "124cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 서해구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "블랙박스, 휴대폰 거치대",
    "maintenance_summary": "엔진오일",
    "posted_days": 0,
    "sheet_row": 35
  },
  {
    "scenario_id": "bike-v08-36",
    "image_file": "v08/bike-v08-36.webp",
    "title": "혼다 CB 650 R E-CLUTCH",
    "brand": "혼다",
    "model": "CB 650 R E-CLUTCH",
    "year": 2025,
    "mileage_km": 13200,
    "displacement_cc": 649,
    "genre": "네이키드",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "전자제어 수동(E-Clutch)",
    "region": "인천 연수구",
    "price_krw": 10500000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "네이키드",
      "649cc",
      "인천",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "인천 연수구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "ARROW 풀배기, Matris 댐퍼, DZELL USB, 엔진가드, GBRacing 커버, 라디에이터·헤드라이트 가드, 블랙박스 등",
    "maintenance_summary": "2주 전 오일·필터 및 체인장력 점검; 혼다 공식센터 점검; 8월 타이어 교체",
    "posted_days": 0,
    "sheet_row": 36
  },
  {
    "scenario_id": "bike-v08-37",
    "image_file": "v08/bike-v08-37.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2020,
    "mileage_km": 23000,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 송파구",
    "price_krw": 4500000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 송파구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "서류 없음",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "아크라포빅 슬립온(구변완료), 2채널 블랙박스, 거치대, USB포트, XRT 부품, 열선, 경보기, 패드, 텐덤백",
    "maintenance_summary": "2026-07 전체점검·체인·대소기어·브레이크액 교체; 23,000km대 야마루브 오일·필터 교환",
    "posted_days": 1,
    "sheet_row": 37
  },
  {
    "scenario_id": "bike-v08-38",
    "image_file": "v08/bike-v08-38.webp",
    "title": "KTM 390 듀크",
    "brand": "KTM",
    "model": "390 듀크",
    "year": 2023,
    "mileage_km": 3000,
    "displacement_cc": 398,
    "genre": "네이키드",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 용산구",
    "price_krw": 5000000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "KTM",
      "네이키드",
      "398cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 용산구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 거치대",
    "maintenance_summary": "엔진오일·필터",
    "posted_days": 0,
    "sheet_row": 38
  },
  {
    "scenario_id": "bike-v08-39",
    "image_file": "v08/bike-v08-39.webp",
    "title": "혼다 인테그라 750",
    "brand": "혼다",
    "model": "인테그라 750",
    "year": 2015,
    "mileage_km": 60000,
    "displacement_cc": 679,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(DCT)",
    "region": "경기 김포시",
    "price_krw": 4950000,
    "seller_type": "전문 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스쿠터",
      "679cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "바이크허브 김포점 (가상)",
    "seller_address": "경기 김포시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 6,
    "sheet_row": 39
  },
  {
    "scenario_id": "bike-v08-40",
    "image_file": "v08/bike-v08-40.webp",
    "title": "야마하 YZF R3",
    "brand": "야마하",
    "model": "YZF R3",
    "year": 2016,
    "mileage_km": 29000,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기 김포시",
    "price_krw": 3140000,
    "seller_type": "전문 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "바이크허브 김포점 (가상)",
    "seller_address": "경기 김포시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 0,
    "sheet_row": 40
  },
  {
    "scenario_id": "bike-v08-41",
    "image_file": "v08/bike-v08-41.webp",
    "title": "혼다 CBR 600 RR",
    "brand": "혼다",
    "model": "CBR 600 RR",
    "year": 2025,
    "mileage_km": 2800,
    "displacement_cc": 600,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 중구",
    "price_krw": 16500000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "600cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 중구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "제작증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "아크라포빅(소음기 없이 구변), G-1 pro 블랙박스, Puig 스크린, EVOTECH 레버, R&G 가드·슬라이더 등",
    "maintenance_summary": "엔진오일·필터, 타이어",
    "posted_days": 1,
    "sheet_row": 41
  },
  {
    "scenario_id": "bike-v08-42",
    "image_file": "v08/bike-v08-42.webp",
    "title": "스즈키 GSX S 125",
    "brand": "스즈키",
    "model": "GSX S 125",
    "year": 2019,
    "mileage_km": 19000,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기 김포시",
    "price_krw": 2530000,
    "seller_type": "전문 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "네이키드",
      "124cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "바이크허브 김포점 (가상)",
    "seller_address": "경기 김포시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 0,
    "sheet_row": 42
  },
  {
    "scenario_id": "bike-v08-43",
    "image_file": "v08/bike-v08-43.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2024,
    "mileage_km": 70000,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기 파주시",
    "price_krw": 2700000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "경기 파주시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 24,
    "sheet_row": 43
  },
  {
    "scenario_id": "bike-v08-44",
    "image_file": "v08/bike-v08-44.webp",
    "title": "BMW R 1250 GS 어드벤처",
    "brand": "BMW",
    "model": "R 1250 GS 어드벤처",
    "year": 2019,
    "mileage_km": 33500,
    "displacement_cc": 1254,
    "genre": "멀티퍼포즈",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 마포구",
    "price_krw": 20500000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "BMW",
      "멀티퍼포즈",
      "1254cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 마포구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "신차급; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "휴대폰 거치대, 블랙박스, USB포트, 윈드스크린, 핸들열선, 엔진가드",
    "maintenance_summary": "엔진오일·필터",
    "posted_days": 3,
    "sheet_row": 44
  },
  {
    "scenario_id": "bike-v08-45",
    "image_file": "v08/bike-v08-45.webp",
    "title": "할리데이비슨 아이언 883",
    "brand": "할리데이비슨",
    "model": "아이언 883",
    "year": 2008,
    "mileage_km": 42000,
    "displacement_cc": 883,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 종로구",
    "price_krw": 9000000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "할리데이비슨",
      "크루저",
      "883cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 종로구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "서류 없음",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 0,
    "sheet_row": 45
  },
  {
    "scenario_id": "bike-v08-46",
    "image_file": "v08/bike-v08-46.webp",
    "title": "야마하 트리시티 125",
    "brand": "야마하",
    "model": "트리시티 125",
    "year": 2015,
    "mileage_km": 24000,
    "displacement_cc": 125,
    "genre": "삼륜",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기 김포시",
    "price_krw": 1710000,
    "seller_type": "전문 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "삼륜",
      "125cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "바이크허브 김포점 (가상)",
    "seller_address": "경기 김포시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 0,
    "sheet_row": 46
  },
  {
    "scenario_id": "bike-v08-47",
    "image_file": "v08/bike-v08-47.webp",
    "title": "베스파 GTS 300 슈퍼테크",
    "brand": "베스파",
    "model": "GTS 300 슈퍼테크",
    "year": 2020,
    "mileage_km": 23300,
    "displacement_cc": 278,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "부산 사상구",
    "price_krw": 5300000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "베스파",
      "스쿠터",
      "278cc",
      "부산",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "스쿠터랩 사상점 (가상)",
    "seller_address": "부산 사상구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "신차급; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "롱스크린, 바엔드미러, 대구공돌, 시거잭·USB포트, 무선충전 거치대, 블랙박스, 탑박스 등",
    "maintenance_summary": "20가지 이상 성능점검 완료 기재; 엔진·미션 2개월 또는 2,000km 보증 기재",
    "posted_days": 3,
    "sheet_row": 47
  },
  {
    "scenario_id": "bike-v08-48",
    "image_file": "v08/bike-v08-48.webp",
    "title": "스즈키 브이스트롬 650 XT",
    "brand": "스즈키",
    "model": "브이스트롬 650 XT",
    "year": 2017,
    "mileage_km": 36600,
    "displacement_cc": 645,
    "genre": "멀티퍼포즈",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "부산 사상구",
    "price_krw": 7300000,
    "seller_type": "전문 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "멀티퍼포즈",
      "645cc",
      "부산",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "투어링팩토리 부산점 (가상)",
    "seller_address": "부산 사상구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "엔진가드·가방, 2채널 블랙박스·카플레이, 거치대, 보조스크린, 3박스, 아크라포빅(구변완료) 등",
    "maintenance_summary": "기본정비 완료; 앞 타이어 60%, 뒤 타이어 새것",
    "posted_days": 30,
    "sheet_row": 48
  },
  {
    "scenario_id": "bike-v08-49",
    "image_file": "v08/bike-v08-49.webp",
    "title": "혼다 CB 300 R",
    "brand": "혼다",
    "model": "CB 300 R",
    "year": 2020,
    "mileage_km": 29000,
    "displacement_cc": 276,
    "genre": "네이키드",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울 중랑구",
    "price_krw": 2800000,
    "seller_type": "개인 판매",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "네이키드",
      "276cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "개인 판매자",
    "seller_address": "서울 중랑구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용신고 필증",
    "condition_summary": "상태 괜찮음; 제꿍 흔적 있음; 슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 0,
    "sheet_row": 49
  },
  {
    "scenario_id": "bike-v08-50",
    "image_file": "v08/bike-v08-50.webp",
    "title": "스즈키 GSX R 125 ABS",
    "brand": "스즈키",
    "model": "GSX R 125 ABS",
    "year": 2021,
    "mileage_km": 22000,
    "displacement_cc": 124,
    "genre": "스포츠",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기 김포시",
    "price_krw": 2800000,
    "seller_type": "전문 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "124cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": false,
    "source_manifest_version": "sheet-bike-20261008",
    "scenario_version": "v08",
    "seller_name": "바이크허브 김포점 (가상)",
    "seller_address": "경기 김포시",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "",
    "business_hours": "",
    "image_grade": "실매물 사진",
    "image_note": "",
    "image_action": "",
    "documents": "사용폐지 증명서",
    "condition_summary": "상태 괜찮음; 제꿍·슬립·사고 이력 없음",
    "tuning_summary": "미표기",
    "maintenance_summary": "미표기",
    "posted_days": 6,
    "sheet_row": 50
  }
];
