export type BikeScenarioV07Row = {
  scenario_id: string;
  image_file: string;
  title: string;
  brand: string;
  model: string;
  year: number;
  mileage_km: number;
  displacement_cc: number;
  genre: string;
  license_class: string;
  fuel: string;
  transmission: string;
  region: string;
  price_krw: number;
  seller_type: string;
  condition: string;
  certified: string;
  delivery: string;
  quickfilter_tags: readonly string[];
  is_virtual: boolean;
  source_manifest_version: string;
  scenario_version: string;
  seller_name: string;
  seller_address: string;
  seller_contact: string;
  seller_intro: string;
  business_hours: string;
  image_grade: string;
  image_note: string;
  image_action: string;
};

export const bikeScenarioV07 = [
  {
    "scenario_id": "bike-001",
    "image_file": "../../listing-photos/v01/harley_forty_eight_2020.jpg",
    "title": "할리데이비슨 포티에잇48",
    "brand": "할리데이비슨",
    "model": "포티에잇",
    "year": 2020,
    "mileage_km": 12980,
    "displacement_cc": 1202,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "부산 사상구",
    "price_krw": 14800000,
    "seller_type": "개인 판매",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "할리데이비슨",
      "크루저",
      "1202cc",
      "부산",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자",
    "seller_address": "부산광역시 사상구",
    "seller_contact": "앱 채팅 전용",
    "seller_intro": "2026-10-07 사용자 지시 추가 매물(사진 사용자 제공)",
    "business_hours": "협의",
    "image_grade": "A",
    "image_note": "사용자 제공 정측면 사진",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-002",
    "image_file": "bike_listing_002_v01.webp",
    "title": "스즈키 하야부사",
    "brand": "스즈키",
    "model": "하야부사",
    "year": 2022,
    "mileage_km": 13300,
    "displacement_cc": 1340,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남",
    "price_krw": 16500000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "1340cc",
      "경남",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "모토브릿지 창원점 (가상)",
    "seller_address": "경상남도 창원시 성산구 라이더로 202 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스포츠 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-003",
    "image_file": "bike_listing_003_v01.webp",
    "title": "존테스 125 G1",
    "brand": "존테스",
    "model": "125 G1",
    "year": 2023,
    "mileage_km": 14200,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전북",
    "price_krw": 2000000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "존테스",
      "네이키드",
      "124cc",
      "전북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 주말라이더03 (가상)",
    "seller_address": "전북특별자치도 전주시 덕진구 투휠로 303 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본으로 가로 카드 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-004",
    "image_file": "bike_listing_004_v01.webp",
    "title": "두카티 파니갈레 V2",
    "brand": "두카티",
    "model": "파니갈레 V2",
    "year": 2023,
    "mileage_km": 6000,
    "displacement_cc": 955,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "울산",
    "price_krw": 25000000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "두카티",
      "스포츠",
      "955cc",
      "울산",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "바이크허브 울산점 (가상)",
    "seller_address": "울산광역시 남구 모터사이클로 104 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스포츠 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본으로 가로 카드 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-005",
    "image_file": "bike_listing_005_v01.webp",
    "title": "스즈키 버그만 스트리트 125 EX",
    "brand": "스즈키",
    "model": "버그만 스트리트 125 EX",
    "year": 2024,
    "mileage_km": 23644,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 1690000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "스즈키",
      "스쿠터",
      "125cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "스쿠터랩 마포점 (가상)",
    "seller_address": "서울특별시 마포구 스쿠터로 205 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본으로 가로 카드 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-006",
    "image_file": "bike_listing_006_v01.webp",
    "title": "야마하 NMAX 125",
    "brand": "야마하",
    "model": "NMAX 125",
    "year": 2025,
    "mileage_km": 12738,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 3400000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "125cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 출퇴근라이더06 (가상)",
    "seller_address": "서울특별시 용산구 한강바이크로 106 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-007",
    "image_file": "bike_listing_007_v01.webp",
    "title": "베스파 LX 125",
    "brand": "베스파",
    "model": "LX 125",
    "year": 2022,
    "mileage_km": 1500,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 2500000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "베스파",
      "스쿠터",
      "124cc",
      "서울",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "클래식모토 서초점 (가상)",
    "seller_address": "서울특별시 서초구 클래식로 207 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본과 배경 차량으로 주 피사체 구분 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-008",
    "image_file": "bike_listing_008_v01.webp",
    "title": "혼다 CBR650R MT",
    "brand": "혼다",
    "model": "CBR650R MT",
    "year": 2023,
    "mileage_km": 32000,
    "displacement_cc": 649,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "대전",
    "price_krw": 7500000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "649cc",
      "대전",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "레이스온 대전점 (가상)",
    "seller_address": "대전광역시 유성구 레이싱로 108 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스포츠 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "C",
    "image_note": "차대번호 라벨 중심으로 차량 형태를 확인할 수 없음",
    "image_action": "교체 필요"
  },
  {
    "scenario_id": "bike-009",
    "image_file": "bike_listing_009_v02.webp",
    "title": "야마하 YZF-R3",
    "brand": "야마하",
    "model": "YZF-R3",
    "year": 2020,
    "mileage_km": 41500,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경북",
    "price_krw": 1300000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 스포츠라이더09 (가상)",
    "seller_address": "경상북도 구미시 스포츠바이크로 209 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "A",
    "image_note": "동일 매물 갤러리의 측면 전체 차량 사진으로 교체함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-010",
    "image_file": "bike_listing_010_v01.webp",
    "title": "야마하 MT-09 트레이서",
    "brand": "야마하",
    "model": "MT-09 트레이서",
    "year": 2015,
    "mileage_km": 37245,
    "displacement_cc": 847,
    "genre": "투어러",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 6000000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "투어러",
      "847cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "투어링팩토리 수원점 (가상)",
    "seller_address": "경기도 수원시 권선구 투어링로 110 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "투어러 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-011",
    "image_file": "bike_listing_011_v01.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2025,
    "mileage_km": 36014,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 4780000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "XMAX랩 용산점 (가상)",
    "seller_address": "서울특별시 용산구 스쿠터로 211 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-012",
    "image_file": "bike_listing_012_v01.webp",
    "title": "야마하 NMAX 155",
    "brand": "야마하",
    "model": "NMAX 155",
    "year": 2026,
    "mileage_km": 2600,
    "displacement_cc": 155,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "대전",
    "price_krw": 5200000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "155cc",
      "대전",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 시티라이더12 (가상)",
    "seller_address": "대전광역시 서구 시티바이크로 112 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "B",
    "image_note": "전면 중심 세로 사진으로 측면 형태 확인이 어려움",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-013",
    "image_file": "bike_listing_013_v01.webp",
    "title": "야마하 NMAX 125",
    "brand": "야마하",
    "model": "NMAX 125",
    "year": 2023,
    "mileage_km": 9400,
    "displacement_cc": 125,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기",
    "price_krw": 2800000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "125cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "라이더스퀘어 분당점 (가상)",
    "seller_address": "경기도 성남시 분당구 스쿠터로 213 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "전면 중심 세로 사진으로 측면 형태 확인이 어려움",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-014",
    "image_file": "bike_listing_014_v01.webp",
    "title": "할리데이비슨 스트리트 밥",
    "brand": "할리데이비슨",
    "model": "스트리트 밥",
    "year": 2025,
    "mileage_km": 4500,
    "displacement_cc": 1868,
    "genre": "크루저",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "인천",
    "price_krw": 24000000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "할리데이비슨",
      "크루저",
      "1868cc",
      "인천",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "크루저하우스 송도점 (가상)",
    "seller_address": "인천광역시 연수구 크루저로 114 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "크루저 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본으로 가로 카드 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-015",
    "image_file": "bike_listing_015_v01.webp",
    "title": "가와사키 버시스-X 250",
    "brand": "가와사키",
    "model": "버시스-X 250",
    "year": 2017,
    "mileage_km": 30500,
    "displacement_cc": 248,
    "genre": "투어러",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전북",
    "price_krw": 3100000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "가와사키",
      "투어러",
      "248cc",
      "전북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 투어러15 (가상)",
    "seller_address": "전북특별자치도 익산시 어드벤처로 215 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "B",
    "image_note": "전면 중심 세로 사진으로 전체 길이 확인이 어려움",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-016",
    "image_file": "bike_listing_016_v01.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2025,
    "mileage_km": 3006,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 6900000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "서울",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "바이크허브 용산점 (가상)",
    "seller_address": "서울특별시 용산구 이륜차로 116 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-017",
    "image_file": "bike_listing_017_v01.webp",
    "title": "혼다 XZ 100",
    "brand": "혼다",
    "model": "XZ 100",
    "year": 2006,
    "mileage_km": 13000,
    "displacement_cc": 99,
    "genre": "언더본",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "부산",
    "price_krw": 1500000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "언더본",
      "99cc",
      "부산",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "클래식모토 부산점 (가상)",
    "seller_address": "부산광역시 사상구 클래식바이크로 217 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "언더본 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "주행 장면과 인물이 포함되어 정적 카드 식별성이 낮음",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-018",
    "image_file": "bike_listing_018_v01.webp",
    "title": "KTM 125 듀크",
    "brand": "KTM",
    "model": "125 듀크",
    "year": 2023,
    "mileage_km": 2500,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "전남",
    "price_krw": 3300000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "KTM",
      "네이키드",
      "124cc",
      "전남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 네이키드라이더18 (가상)",
    "seller_address": "전라남도 순천시 네이키드로 118 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본으로 가로 카드 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-019",
    "image_file": "bike_listing_019_v02.webp",
    "title": "혼다 CBR650R E-Clutch",
    "brand": "혼다",
    "model": "CBR650R E-Clutch",
    "year": 2025,
    "mileage_km": 8800,
    "displacement_cc": 649,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "전자제어 수동(E-Clutch)",
    "region": "서울",
    "price_krw": 10800000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "스포츠",
      "649cc",
      "서울",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "스포츠모토 강동점 (가상)",
    "seller_address": "서울특별시 강동구 스포츠로 219 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스포츠 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "동일 매물 갤러리의 전체 차량 사진으로 교체했으나 세로 원본 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-020",
    "image_file": "bike_listing_020_v01.webp",
    "title": "혼다 MSX125 그롬",
    "brand": "혼다",
    "model": "MSX125 그롬",
    "year": 2025,
    "mileage_km": 204,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 3600000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "네이키드",
      "124cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "모토브릿지 용산점 (가상)",
    "seller_address": "서울특별시 용산구 미니바이크로 120 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "네이키드 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-021",
    "image_file": "bike_listing_021_v01.webp",
    "title": "야마하 YZF-R3",
    "brand": "야마하",
    "model": "YZF-R3",
    "year": 2018,
    "mileage_km": 36314,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남",
    "price_krw": 2800000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 R3라이더21 (가상)",
    "seller_address": "경상남도 김해시 레이싱로 221 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-022",
    "image_file": "bike_listing_022_v01.webp",
    "title": "가와사키 닌자 400 ABS",
    "brand": "가와사키",
    "model": "닌자 400 ABS",
    "year": 2019,
    "mileage_km": 25987,
    "displacement_cc": 399,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "대구",
    "price_krw": 5000000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "가와사키",
      "스포츠",
      "399cc",
      "대구",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "레이스온 대구점 (가상)",
    "seller_address": "대구광역시 달서구 닌자로 122 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스포츠 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "여러 차량이 함께 있어 대상 식별에 주의가 필요함",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-023",
    "image_file": "bike_listing_023_v01.webp",
    "title": "베스파 스프린트 125 저스틴 비버 에디션",
    "brand": "베스파",
    "model": "스프린트 125 저스틴 비버 에디션",
    "year": 2022,
    "mileage_km": 7999,
    "displacement_cc": 124,
    "genre": "스쿠터",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "서울",
    "price_krw": 5000000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "베스파",
      "스쿠터",
      "124cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "스쿠터랩 강남점 (가상)",
    "seller_address": "서울특별시 강남구 스쿠터로 223 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "세로 원본으로 가로 카드 크롭 주의",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-024",
    "image_file": "bike_listing_024_v01.webp",
    "title": "혼다 C125",
    "brand": "혼다",
    "model": "C125",
    "year": 2025,
    "mileage_km": 21116,
    "displacement_cc": 124,
    "genre": "언더본",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 2800000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "혼다",
      "언더본",
      "124cc",
      "서울",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 커브라이더24 (가상)",
    "seller_address": "서울특별시 동대문구 커브로 124 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-025",
    "image_file": "bike_listing_025_v01.webp",
    "title": "가와사키 닌자 1000SX",
    "brand": "가와사키",
    "model": "닌자 1000SX",
    "year": 2020,
    "mileage_km": 27129,
    "displacement_cc": 1043,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 10550000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "가와사키",
      "스포츠",
      "1043cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "그랜드투어링 일산점 (가상)",
    "seller_address": "경기도 고양시 일산동구 투어링로 225 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스포츠 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-026",
    "image_file": "bike_listing_026_v01.webp",
    "title": "야마하 XMAX 300 ABS",
    "brand": "야마하",
    "model": "XMAX 300 ABS",
    "year": 2023,
    "mileage_km": 58000,
    "displacement_cc": 292,
    "genre": "스쿠터",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "자동(CVT)",
    "region": "경기",
    "price_krw": 4200000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "야마하",
      "스쿠터",
      "292cc",
      "경기",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "XMAX랩 안양점 (가상)",
    "seller_address": "경기도 안양시 동안구 스쿠터로 126 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "스쿠터 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "B",
    "image_note": "전면 중심 세로 사진으로 측면 형태 확인이 어려움",
    "image_action": "보완 권장"
  },
  {
    "scenario_id": "bike-027",
    "image_file": "bike_listing_027_v01.webp",
    "title": "야마하 YZF-R3",
    "brand": "야마하",
    "model": "YZF-R3",
    "year": 2019,
    "mileage_km": 33800,
    "displacement_cc": 321,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경남",
    "price_krw": 4450000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "야마하",
      "스포츠",
      "321cc",
      "경남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 스포츠라이더27 (가상)",
    "seller_address": "경상남도 창원시 의창구 스포츠로 227 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "C",
    "image_note": "구동계 클로즈업으로 차량 전체 확인이 어려움",
    "image_action": "교체 필요"
  },
  {
    "scenario_id": "bike-028",
    "image_file": "bike_listing_028_v01.webp",
    "title": "KR모터스 아퀼라 125",
    "brand": "KR모터스",
    "model": "아퀼라 125",
    "year": 2020,
    "mileage_km": 2048,
    "displacement_cc": 124,
    "genre": "크루저",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 2250000,
    "seller_type": "전문 판매업체",
    "condition": "상",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "KR모터스",
      "크루저",
      "124cc",
      "경기",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "아퀼라하우스 화성점 (가상)",
    "seller_address": "경기도 화성시 크루저로 128 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "크루저 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-029",
    "image_file": "bike_listing_029_v01.webp",
    "title": "혼다 MSX125 SF",
    "brand": "혼다",
    "model": "MSX125 SF",
    "year": 2017,
    "mileage_km": 21500,
    "displacement_cc": 124,
    "genre": "네이키드",
    "license_class": "원동기 이상",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "서울",
    "price_krw": 1700000,
    "seller_type": "인증 판매업체",
    "condition": "중상",
    "certified": "가능",
    "delivery": "탁송 가능",
    "quickfilter_tags": [
      "혼다",
      "네이키드",
      "124cc",
      "서울",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "미니모토 광진점 (가상)",
    "seller_address": "서울특별시 광진구 미니바이크로 229 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "네이키드 점검·탁송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00, 토요일 예약제 (가상)",
    "image_grade": "A",
    "image_note": "차량 전체가 명확함",
    "image_action": "유지"
  },
  {
    "scenario_id": "bike-030",
    "image_file": "bike_listing_030_v01.webp",
    "title": "스즈키 하야부사",
    "brand": "스즈키",
    "model": "하야부사",
    "year": 2022,
    "mileage_km": 24000,
    "displacement_cc": 1340,
    "genre": "스포츠",
    "license_class": "2종 소형",
    "fuel": "가솔린",
    "transmission": "수동",
    "region": "경기",
    "price_krw": 18500000,
    "seller_type": "개인 판매",
    "condition": "중",
    "certified": "해당 없음",
    "delivery": "직접 인수",
    "quickfilter_tags": [
      "스즈키",
      "스포츠",
      "1340cc",
      "경기",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v07",
    "seller_name": "개인 판매자 하야부사라이더30 (가상)",
    "seller_address": "경기도 용인시 기흥구 하야부사로 130 (가상 주소)",
    "seller_contact": "앱 채팅 전용 (가상)",
    "seller_intro": "개인 간 직거래 화면 검증용 가상 판매자 프로필",
    "business_hours": "예약 후 협의 (가상)",
    "image_grade": "B",
    "image_note": "주행 장면과 모션 블러로 정적 카드 식별성이 낮음",
    "image_action": "보완 권장"
  }
] as const satisfies readonly BikeScenarioV07Row[];
