export type HeavyScenarioV04Row = {
  scenario_id: string;
  image_file: string;
  title: string;
  manufacturer: string;
  model: string;
  equipment_type: string;
  detail_type: string;
  year: number;
  operating_hours: number;
  region: string;
  price_10k_krw: number;
  seller_type: string;
  condition: string;
  inspection: string;
  delivery: string;
  quickfilter_tags: readonly string[];
  is_virtual: boolean;
  source_manifest_version: string;
  scenario_version: string;
  seller_name: string;
  seller_address: string;
  seller_contact: string;
  seller_intro: string;
  business_hours: string;
};

export const heavyScenarioV04 = [
  {
    "scenario_id": "heavy-001",
    "image_file": "../../listing-photos/v01/volvo_ew60e_2017.jpg",
    "title": "EW60E",
    "manufacturer": "볼보",
    "model": "EW60E",
    "equipment_type": "굴삭기",
    "detail_type": "타이어식",
    "year": 2017,
    "operating_hours": 880,
    "region": "경북",
    "price_10k_krw": 5650,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "타이어식",
      "2017",
      "경북",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "중기파트너 경기 01점 (가상)",
    "seller_address": "경기도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-002",
    "image_file": "heavy_listing_002_v01.jpg",
    "title": "EC480E",
    "manufacturer": "볼보",
    "model": "EC480E",
    "equipment_type": "굴삭기",
    "detail_type": "1.3㎥ 이상",
    "year": 2016,
    "operating_hours": 2237,
    "region": "인천",
    "price_10k_krw": 18800,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "1.3㎥ 이상",
      "2016",
      "인천",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "헤비웍스 인천 02점 (가상)",
    "seller_address": "인천광역시 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-003",
    "image_file": "heavy_listing_003_v01.jpg",
    "title": "EC380D",
    "manufacturer": "볼보",
    "model": "EC380D",
    "equipment_type": "굴삭기",
    "detail_type": "1.3㎥ 이상",
    "year": 2017,
    "operating_hours": 2674,
    "region": "충남",
    "price_10k_krw": 4000,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "1.3㎥ 이상",
      "2017",
      "충남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인003 (가상)",
    "seller_address": "충청남도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-004",
    "image_file": "heavy_listing_004_v01.jpg",
    "title": "HX300A",
    "manufacturer": "현대",
    "model": "HX300A",
    "equipment_type": "굴삭기",
    "detail_type": "1.0㎥ 이상",
    "year": 2018,
    "operating_hours": 3111,
    "region": "전북",
    "price_10k_krw": 7800,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "1.0㎥ 이상",
      "2018",
      "전북",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "장비브릿지 전북 04점 (가상)",
    "seller_address": "전북특별자치도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-005",
    "image_file": "heavy_listing_005_v01.jpg",
    "title": "hx300특급",
    "manufacturer": "현대",
    "model": "hx300특급",
    "equipment_type": "굴삭기",
    "detail_type": "1.0㎥ 이상",
    "year": 2019,
    "operating_hours": 3548,
    "region": "경남",
    "price_10k_krw": 6000,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "1.0㎥ 이상",
      "2019",
      "경남",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "현장모터스 경남 05점 (가상)",
    "seller_address": "경상남도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-006",
    "image_file": "heavy_listing_006_v01.jpg",
    "title": "R300LC",
    "manufacturer": "현대",
    "model": "R300LC",
    "equipment_type": "굴삭기",
    "detail_type": "1.0㎥ 이상",
    "year": 2020,
    "operating_hours": 3985,
    "region": "대구",
    "price_10k_krw": 4200,
    "seller_type": "개인 판매",
    "condition": "A급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "1.0㎥ 이상",
      "2020",
      "대구",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인006 (가상)",
    "seller_address": "대구광역시 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-007",
    "image_file": "heavy_listing_007_v01.jpg",
    "title": "ECR145숏붐",
    "manufacturer": "볼보",
    "model": "ECR145숏붐",
    "equipment_type": "굴삭기",
    "detail_type": "0.4~0.9㎥",
    "year": 2021,
    "operating_hours": 4422,
    "region": "부산",
    "price_10k_krw": 2750,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "0.4~0.9㎥",
      "2021",
      "부산",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "헤비웍스 부산 07점 (가상)",
    "seller_address": "부산광역시 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-008",
    "image_file": "heavy_listing_008_v01.jpeg",
    "title": "Dx140표준붐",
    "manufacturer": "디벨론",
    "model": "Dx140표준붐",
    "equipment_type": "굴삭기",
    "detail_type": "0.4~0.9㎥",
    "year": 2022,
    "operating_hours": 4859,
    "region": "강원",
    "price_10k_krw": 7700,
    "seller_type": "인증 판매업체",
    "condition": "A급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "0.4~0.9㎥",
      "2022",
      "강원",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "건설기계 허브 강원 08점 (가상)",
    "seller_address": "강원특별자치도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-009",
    "image_file": "heavy_listing_009_v01.jpg",
    "title": "SK75코집회전",
    "manufacturer": "코벨코",
    "model": "SK75코집회전",
    "equipment_type": "굴삭기",
    "detail_type": "0.4~0.9㎥",
    "year": 2023,
    "operating_hours": 5296,
    "region": "충북",
    "price_10k_krw": 3500,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "0.4~0.9㎥",
      "2023",
      "충북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인009 (가상)",
    "seller_address": "충청북도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-010",
    "image_file": "heavy_listing_010_v01.jpg",
    "title": "55MT코집특",
    "manufacturer": "미확인",
    "model": "55MT코집특",
    "equipment_type": "굴삭기",
    "detail_type": "0.3㎥ 이하",
    "year": 2024,
    "operating_hours": 5733,
    "region": "전남",
    "price_10k_krw": 2750,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "0.3㎥ 이하",
      "2024",
      "전남",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "현장모터스 전남 10점 (가상)",
    "seller_address": "전라남도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-011",
    "image_file": "heavy_listing_011_v01.jpg",
    "title": "EC60E집게",
    "manufacturer": "볼보",
    "model": "EC60E집게",
    "equipment_type": "굴삭기",
    "detail_type": "0.3㎥ 이하",
    "year": 2025,
    "operating_hours": 6170,
    "region": "경기",
    "price_10k_krw": 3100,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "0.3㎥ 이하",
      "2025",
      "경기",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "중기파트너 경기 11점 (가상)",
    "seller_address": "경기도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-012",
    "image_file": "heavy_listing_012_v01.jpg",
    "title": "EC65F풀셋",
    "manufacturer": "볼보",
    "model": "EC65F풀셋",
    "equipment_type": "굴삭기",
    "detail_type": "0.3㎥ 이하",
    "year": 2015,
    "operating_hours": 6607,
    "region": "인천",
    "price_10k_krw": 6900,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "0.3㎥ 이하",
      "2015",
      "인천",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인012 (가상)",
    "seller_address": "인천광역시 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-013",
    "image_file": "heavy_listing_013_v01.jpg",
    "title": "U20",
    "manufacturer": "구보다",
    "model": "U20",
    "equipment_type": "미니굴삭기",
    "detail_type": "미니굴삭기",
    "year": 2016,
    "operating_hours": 7044,
    "region": "충남",
    "price_10k_krw": 2000,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "미니굴삭기",
      "미니굴삭기",
      "2016",
      "충남",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "건설기계 허브 충남 13점 (가상)",
    "seller_address": "충청남도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-014",
    "image_file": "heavy_listing_014_v01.jpg",
    "title": "SK35코집",
    "manufacturer": "코벨코",
    "model": "SK35코집",
    "equipment_type": "미니굴삭기",
    "detail_type": "미니굴삭기",
    "year": 2017,
    "operating_hours": 7481,
    "region": "전북",
    "price_10k_krw": 2100,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "미니굴삭기",
      "미니굴삭기",
      "2017",
      "전북",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "장비브릿지 전북 14점 (가상)",
    "seller_address": "전북특별자치도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-015",
    "image_file": "heavy_listing_015_v01.jpg",
    "title": "U20저비용",
    "manufacturer": "구보다",
    "model": "U20저비용",
    "equipment_type": "미니굴삭기",
    "detail_type": "미니굴삭기",
    "year": 2018,
    "operating_hours": 7918,
    "region": "경남",
    "price_10k_krw": 1800,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "미니굴삭기",
      "미니굴삭기",
      "2018",
      "경남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인015 (가상)",
    "seller_address": "경상남도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-016",
    "image_file": "heavy_listing_016_v01.jpg",
    "title": "DX55W대쪽",
    "manufacturer": "디벨론",
    "model": "DX55W대쪽",
    "equipment_type": "굴삭기",
    "detail_type": "타이어식",
    "year": 2019,
    "operating_hours": 8355,
    "region": "대구",
    "price_10k_krw": 6700,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "타이어식",
      "2019",
      "대구",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "중기파트너 대구 16점 (가상)",
    "seller_address": "대구광역시 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-017",
    "image_file": "heavy_listing_017_v01.jpg",
    "title": "160W독회링어",
    "manufacturer": "미확인",
    "model": "160W독회링어",
    "equipment_type": "굴삭기",
    "detail_type": "타이어식",
    "year": 2020,
    "operating_hours": 8792,
    "region": "부산",
    "price_10k_krw": 8800,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "굴삭기",
      "타이어식",
      "2020",
      "부산",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "헤비웍스 부산 17점 (가상)",
    "seller_address": "부산광역시 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-018",
    "image_file": "heavy_listing_018_v01.png",
    "title": "HW155회링집",
    "manufacturer": "현대",
    "model": "HW155회링집",
    "equipment_type": "굴삭기",
    "detail_type": "타이어식",
    "year": 2021,
    "operating_hours": 9229,
    "region": "강원",
    "price_10k_krw": 14700,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "굴삭기",
      "타이어식",
      "2021",
      "강원",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인018 (가상)",
    "seller_address": "강원특별자치도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-019",
    "image_file": "heavy_listing_019_v01.jpeg",
    "title": "08대바가지",
    "manufacturer": "미확인",
    "model": "08대바가지",
    "equipment_type": "어태치먼트",
    "detail_type": "굴삭기 어태치먼트",
    "year": 2022,
    "operating_hours": 9666,
    "region": "충북",
    "price_10k_krw": 300,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "어태치먼트",
      "굴삭기 어태치먼트",
      "2022",
      "충북",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "장비브릿지 충북 19점 (가상)",
    "seller_address": "충청북도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-020",
    "image_file": "heavy_listing_020_v01.jpg",
    "title": "수산브레이커87",
    "manufacturer": "미확인",
    "model": "수산브레이커87",
    "equipment_type": "어태치먼트",
    "detail_type": "굴삭기 어태치먼트",
    "year": 2023,
    "operating_hours": 1903,
    "region": "전남",
    "price_10k_krw": 850,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "어태치먼트",
      "굴삭기 어태치먼트",
      "2023",
      "전남",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "현장모터스 전남 20점 (가상)",
    "seller_address": "전라남도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-021",
    "image_file": "heavy_listing_021_v01.jpeg",
    "title": "760IT",
    "manufacturer": "미확인",
    "model": "760IT",
    "equipment_type": "어태치먼트",
    "detail_type": "굴삭기 어태치먼트",
    "year": 2024,
    "operating_hours": 2340,
    "region": "경기",
    "price_10k_krw": 3200,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "어태치먼트",
      "굴삭기 어태치먼트",
      "2024",
      "경기",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인021 (가상)",
    "seller_address": "경기도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-022",
    "image_file": "heavy_listing_022_v01.jpg",
    "title": "중고공구리통",
    "manufacturer": "미확인",
    "model": "중고공구리통",
    "equipment_type": "부속품",
    "detail_type": "굴삭기 부속",
    "year": 2025,
    "operating_hours": 2777,
    "region": "인천",
    "price_10k_krw": 150,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "부속품",
      "굴삭기 부속",
      "2025",
      "인천",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "헤비웍스 인천 22점 (가상)",
    "seller_address": "인천광역시 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-023",
    "image_file": "heavy_listing_023_v01.jpg",
    "title": "R500특A",
    "manufacturer": "현대",
    "model": "R500특A",
    "equipment_type": "덤프트럭",
    "detail_type": "19톤 이상",
    "year": 2015,
    "operating_hours": 3214,
    "region": "충남",
    "price_10k_krw": 9400,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "덤프트럭",
      "19톤 이상",
      "2015",
      "충남",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "건설기계 허브 충남 23점 (가상)",
    "seller_address": "충청남도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-024",
    "image_file": "heavy_listing_024_v01.jpg",
    "title": "3대460FM",
    "manufacturer": "미확인",
    "model": "3대460FM",
    "equipment_type": "덤프트럭",
    "detail_type": "19톤 이상",
    "year": 2016,
    "operating_hours": 3651,
    "region": "전북",
    "price_10k_krw": 4600,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "덤프트럭",
      "19톤 이상",
      "2016",
      "전북",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인024 (가상)",
    "seller_address": "전북특별자치도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-025",
    "image_file": "heavy_listing_025_v01.jpg",
    "title": "440영업용",
    "manufacturer": "미확인",
    "model": "440영업용",
    "equipment_type": "덤프트럭",
    "detail_type": "19톤 이상",
    "year": 2017,
    "operating_hours": 4088,
    "region": "경남",
    "price_10k_krw": 3500,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "덤프트럭",
      "19톤 이상",
      "2017",
      "경남",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "현장모터스 경남 25점 (가상)",
    "seller_address": "경상남도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-026",
    "image_file": "heavy_listing_026_v01.jpeg",
    "title": "파워텍380",
    "manufacturer": "현대",
    "model": "파워텍380",
    "equipment_type": "덤프트럭",
    "detail_type": "16톤 이하",
    "year": 2018,
    "operating_hours": 4525,
    "region": "대구",
    "price_10k_krw": 2000,
    "seller_type": "인증 판매업체",
    "condition": "A급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "덤프트럭",
      "16톤 이하",
      "2018",
      "대구",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "중기파트너 대구 26점 (가상)",
    "seller_address": "대구광역시 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-027",
    "image_file": "heavy_listing_027_v01.jpg",
    "title": "프리마.410",
    "manufacturer": "타타대우",
    "model": "프리마.410",
    "equipment_type": "덤프트럭",
    "detail_type": "16톤 이하",
    "year": 2019,
    "operating_hours": 4962,
    "region": "부산",
    "price_10k_krw": 5200,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "덤프트럭",
      "16톤 이하",
      "2019",
      "부산",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인027 (가상)",
    "seller_address": "부산광역시 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-028",
    "image_file": "heavy_listing_028_v01.jpg",
    "title": "파워자가용제설무",
    "manufacturer": "미확인",
    "model": "파워자가용제설무",
    "equipment_type": "덤프트럭",
    "detail_type": "16톤 이하",
    "year": 2020,
    "operating_hours": 5399,
    "region": "강원",
    "price_10k_krw": 8200,
    "seller_type": "전문 판매업체",
    "condition": "A+급",
    "inspection": "점검표 제공",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "덤프트럭",
      "16톤 이하",
      "2020",
      "강원",
      "전문 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "건설기계 허브 강원 28점 (가상)",
    "seller_address": "강원특별자치도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-029",
    "image_file": "heavy_listing_029_v01.jpg",
    "title": "메가저상롱덤프",
    "manufacturer": "현대",
    "model": "메가저상롱덤프",
    "equipment_type": "덤프트럭",
    "detail_type": "10톤 이하",
    "year": 2021,
    "operating_hours": 5836,
    "region": "충북",
    "price_10k_krw": 5200,
    "seller_type": "인증 판매업체",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "운송 협의",
    "quickfilter_tags": [
      "덤프트럭",
      "10톤 이하",
      "2021",
      "충북",
      "인증 판매업체"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "장비브릿지 충북 29점 (가상)",
    "seller_address": "충청북도 가상시 테스트구 건설기계 전시장 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  },
  {
    "scenario_id": "heavy-030",
    "image_file": "heavy_listing_030_v01.jpg",
    "title": "5M10저상덤프",
    "manufacturer": "미확인",
    "model": "5M10저상덤프",
    "equipment_type": "덤프트럭",
    "detail_type": "10톤 이하",
    "year": 2022,
    "operating_hours": 6273,
    "region": "전남",
    "price_10k_krw": 5100,
    "seller_type": "개인 판매",
    "condition": "A+급",
    "inspection": "현장 확인",
    "delivery": "현장 인수",
    "quickfilter_tags": [
      "덤프트럭",
      "10톤 이하",
      "2022",
      "전남",
      "개인 판매"
    ],
    "is_virtual": true,
    "source_manifest_version": "v01",
    "scenario_version": "v04",
    "seller_name": "개인 판매자 장비인030 (가상)",
    "seller_address": "전라남도 가상시 테스트구 건설기계 직거래 지점 (가상 주소)",
    "seller_contact": "앱 채팅만 사용 (가상)",
    "seller_intro": "건설기계 점검·운송 상담용 가상 판매자 프로필",
    "business_hours": "평일 09:00~18:00 (가상)"
  }
] as const satisfies readonly HeavyScenarioV04Row[];
